### ISSUE TITLE
NPE observed during local theme testing.

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1035]
Hello PlantUML team,

Here is a **NPE** during _local theme_ testing, observed on `v1.2021.7` and `v1.2022.6beta5`:

- Local missing theme seems KO: ➡️ [Link to PlantUML server output](http://www.plantuml.com/plantuml/uml/SoWkIImgAStDuL8ioKZDJLL8J5H8AyhFLT07Sukv75BpKe3I0000)
```puml
@startuml
!theme aa from /themes
@enduml
```

```.cy
aa.puml:2:error:Fatal parsing error
java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.BufferedReader.<init>(BufferedReader.java:101)
	at java.base/java.io.BufferedReader.<init>(BufferedReader.java:116)
	at net.sourceforge.plantuml.preproc.ReadLineReader.<init>(ReadLineReader.java:57)
	at net.sourceforge.plantuml.preproc.ReadLineReader.create(ReadLineReader.java:73)
	at net.sourceforge.plantuml.tim.EaterTheme.getTheme(EaterTheme.java:97)
	at net.sourceforge.plantuml.tim.TContext.executeTheme(TContext.java:573)
	at net.sourceforge.plantuml.tim.TContext.executeOneLineNotSafe(TContext.java:287)
	at net.sourceforge.plantuml.tim.TContext.executeOneLineSafe(TContext.java:268)
	at net.sourceforge.plantuml.tim.TContext.executeLines(TContext.java:239)
	at net.sourceforge.plantuml.tim.TimLoader.load(TimLoader.java:66)
	at net.sourceforge.plantuml.BlockUml.<init>(BlockUml.java:124)
	at net.sourceforge.plantuml.BlockUmlBuilder.init(BlockUmlBuilder.java:123)
	at net.sourceforge.plantuml.BlockUmlBuilder.<init>(BlockUmlBuilder.java:74)
	at net.sourceforge.plantuml.SourceFileReader.<init>(SourceFileReader.java:91)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:489)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:403)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:370)
	at net.sourceforge.plantuml.Run.main(Run.java:198)
```
_[Output from v1.2021.7]_

- Global missing theme seems OK:
```puml
@startuml
!theme aa
@enduml
```
```.pir
aa.puml:2:error:No such theme aa
```

_Thanks for the error management enhancement._
Regards.

**Comment by The-Lum** [comment]
Seems be fixed by:
- https://github.com/plantuml/plantuml/commit/e801884415e0887782489934a2f8e12bf970a795#diff-995a5028b781f2fcda71a12cb369366b75d2a2d78ef2d0e22c685c7dc0323326

Thanks.
