### ISSUE TITLE
Allow Arrows in any direction

### ISSUE THREAD

**Issue by xeruf** [plantuml/plantuml#1078]
Default Arrows prefer to go horizontally, which quickly creates a mess and prompts manual layout intervention by adding directions to arrows. 

If I create a simple diagram like this:
```sh
One - Two
Three - Two
Three - Four
Five - Four
Five - One
```
I would actually expect them to form a pentagon, as this would make it very aesthetically pleasing. Maybe a flag that makes default lines directionless?

**Comment by xeruf** [comment]
Hey, I would love to use PlantUML professionally, any chance of progress here? :)

**Comment by arnaudroques** [comment]
> Hey, I would love to use PlantUML professionally, any chance of progress here? :)

Unfortunately, no chance here.
The layout in computed by GraphViz. And GraphViz does not allow this.
Sorry about that!

**Comment by xeruf** [comment]
hm, what about something like https://graphviz.org/docs/layouts/circo and https://graphviz.org/docs/layouts/neato ? Would it be hard to use different graphviz layouts?

**Comment by xeruf** [comment]
so, I kinda managed to but plantuml complains:
```sh
❯ plantuml -graphvizdot "$(which neato)" vikunja.plantuml
Picked up _JAVA_OPTIONS: -Djava.util.prefs.userRoot=/home/janek/.config/java
Exception java.lang.IllegalStateException: Cannot find color #000004
net.sourceforge.plantuml.cucadiagram.UnparsableGraphvizException: java.lang.IllegalStateException: Cannot find color #000004
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:468)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:102)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:67)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:610)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:189)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:134)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:180)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:517)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:400)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:367)
	at net.sourceforge.plantuml.Run.main(Run.java:202)
Caused by: java.lang.IllegalStateException: Cannot find color #000004
	at net.sourceforge.plantuml.svek.DotStringFactory.getClusterIndex(DotStringFactory.java:465)
	at net.sourceforge.plantuml.svek.DotStringFactory.solve(DotStringFactory.java:423)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:462)
	... 13 more
```

**Comment by xeruf** [comment]
I hacked it together to this, which does not look promising :/

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/13354331/187986810-8885a80c-85b4-488f-bf57-9e345d335c90.png">

**Comment by xeruf** [comment]
Interestingly Smetana already produces a different, better result :)

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/13354331/188129907-864aa3cb-a9c5-4871-9856-49315deb66aa.png">
