### ISSUE TITLE
Failed to generate image: PlantUML preprocessing failed: [From <input> (line 21) ]

### ISSUE THREAD

**Issue by nfrankel** [plantuml/plantuml#1082]
Hello,

I'm faced with the following issue:

```
package java.lang {
 class Throwable {
  + getMessage(): String
  + getLocalizedMessage(): String
 }
 class StackTraceElement {
  + getClassLoaderName(): String
  + getClassName(): String
  + getFileName(): String
  + getLineNumber(): int
  + getMethodName(): String
  + getModuleName(): String
  + getModuleVersion(): String
  + isNativeMethod(): boolean
 }
 class RuntimeException
 class Exception
 note "RuntimeException and all its\nsub-classes are unchecked exceptions" as noteex
}
Throwable -left-> "*" StackTraceElement
^^^^^
 You should send a mail to plantuml@gmail.com or post to http://plantuml.com/qa with this log (V1.2022.5) java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1

package java.lang {
 class Throwable {
  + getMessage(): String
  + getLocalizedMessage(): String
 }
 class StackTraceElement {
  + getClassLoaderName(): String
  + getClassName(): String
  + getFileName(): String
  + getLineNumber(): int
  + getMethodName(): String
  + getModuleName(): String
  + getModuleVersion(): String
  + isNativeMethod(): boolean
 }
 class RuntimeException
 class Exception
 note "RuntimeException and all its\nsub-classes are unchecked exceptions" as noteex
}
Throwable -left-> "*" StackTraceElement
Throwable --> "0..1" Throwable: cause
Exception -up-|> Throwable
RuntimeException -up-|> Exception
noteex .right. RuntimeException
hide empty members
```

## Context

I'm using PlantUML inside `asciidoctor-diagram-plantuml` on my Jekyll blog.

With version 1.2022.1, it works both:

* Locally: Ruby 3.1.1 & JVM
* Remotely (on GitLab): JRuby 9.3-jre11 in Docker

With version 1.2022.5, it still works locally but not remotely.

I'd be very grateful for any hint. Feel free to ask additional questions.

**Comment by nfrankel** [comment]
What additional details would you need to reproduct? I've given as much context as I could

**Comment by arnaudroques** [comment]
Thanks for the report.
This is weird :-)

First, you could try to get the "shortest diagram that shows the issue".
It would help to understand the issue.

For example, is [the following on still failing](http://www.plantuml.com/plantuml/uml/ROv1IiP034RtSuemIw4UGVvDBw1Tkacddsrj9YsJZ1R4kok54H6tBzyBxsREnMkMS73QU0QzyXlV2-jC7u6Ii1aDIzdVUHGqyEJVuw5mGY_8K6-7nwg-PlHdmk7hhet_0hexAFuT4kj4B4AhsxDQ7RjBX14NKDMq86sO24smI6pNCvpXC_maKYTuyUw1ubtyf_C6dMgMBm00)?

Also, since there is an exception (`java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1`), maybe you can try to see if you have the detail of the stacktrace somewhere ?

Thanks!

**Comment by evantill** [comment]
Using the diagramm as proposed in [previous message](https://github.com/plantuml/plantuml/issues/1082#issuecomment-1477420752) I can not reproduce the error : 

See the screenshot bellow: 

<img width="830" alt="Welcome_to_Jekyll____Your_awesome_title" src="https://user-images.githubusercontent.com/609288/226652791-424d9a8c-b8c4-4889-ac2f-d2132ee8506d.png">

**Comment by nfrankel** [comment]
Thanks for you help.

I noticed that the last working version is `v1.2022.1`. Afterwards, you removed the block delimiting parentheses:

```
	if (format.contains("\"") && s.length() > 1 && isDoubleQuote(s.charAt(0))
				&& isDoubleQuote(s.charAt(s.length() - 1)))
			return s.substring(1, s.length() - 1);
```

I don't see any other differences and the logic is indeed the same.

**Comment by arnaudroques** [comment]
I'm sorry, I am completely confused.

Given those line numbers:
```
	at net.sourceforge.plantuml.StringUtils.eventuallyRemoveStartingAndEndingDoubleQuote(StringUtils.java:298)
	at net.sourceforge.plantuml.StringUtils.eventuallyRemoveStartingAndEndingDoubleQuote(StringUtils.java:307)
```
It looks like you are running a modified or a old version of PlantUML.
For example, depending on the version, I have [this](https://github.com/plantuml/plantuml/blob/39c585ee094d0d5aa83ad6fcb7704e34f7b827b3/src/net/sourceforge/plantuml/StringUtils.java#L298) or [this](https://github.com/plantuml/plantuml/blob/be8454cb59648004544f959e35f26a4c05cfce6d/src/net/sourceforge/plantuml/StringUtils.java#L298) in line 298 and that does not match your stacktrace.
Even [version 1.2022.5](https://github.com/plantuml/plantuml/blob/v1.2022.5/src/net/sourceforge/plantuml/StringUtils.java#L298) does not match your stack trace.

Could you double-check your version with:
```
@startuml
version
@enduml
```

Since the issue is quite old, did you upgrade to last version? It may help.

Keep us informed!

**Comment by nfrankel** [comment]
Everything works fine up until `v1.2022.1`.

I've tried submitting the basic `Bob -> Alice : hello`: it works with neither version `v1.2022.14` nor version `v1.2023.4`.

`v1.2022.2` is the first non-working version.

**Comment by The-Lum** [comment]
@nfrankel 
- Is this issue still present?
