### ISSUE TITLE
Use java.util.logging.Logger instead of printStackTrace

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#1086]
It makes it possible to bridge/route log messages to another logger. Would you be OK with this change? (I can submit a pull request)

**Comment by arnaudroques** [comment]
Sure, that's a good idea.
However, before doing any change, maybe we can discuss about what you are envisioning?
Since PlantUML is used as a library with many tools, we have to be careful not to break any existing behaviour...

For example, maybe this should be disable by default?

Thanks!

**Comment by Mogztter** [comment]
> However, before doing any change, maybe we can discuss about what you are envisioning?
Since PlantUML is used as a library with many tools, we have to be careful not to break any existing behaviour...

If I'm not mistaken it's not possible to disable `printStackTrace` and by default it prints on the standard error stream (i.e., stderr). My idea was to declare a logger with a backward compatible format method:

```java
public class PlantumlLogger {

  public static void main(String[] args) {
    // initialize logger with legacy format
    Logger logger = Logger.getLogger("com.plantuml");
    logger.setUseParentHandlers(false);
    ConsoleHandler handler = new ConsoleHandler();
    handler.setFormatter(new Formatter() {
      @Override
      public synchronized String format(LogRecord lr) {
        String throwable = "";
        if (lr.getThrown() != null) {
          StringWriter sw = new StringWriter();
          PrintWriter pw = new PrintWriter(sw);
          pw.println();
          lr.getThrown().printStackTrace(pw);
          pw.close();
          throwable = sw.toString().trim();
        }
        String message = lr.getMessage();
        StringBuilder sb = new StringBuilder();
        if (message.trim().length() > 0) {
          sb.append(message);
          sb.append(System.lineSeparator());
        }
        if (throwable.length() > 0) {
          sb.append(throwable);
          sb.append(System.lineSeparator());
        }
        return sb.toString();
      }
    });
    logger.addHandler(handler);

    // use logger
    logger.log(Level.SEVERE, "Something went wrong :(", new Exception("Ooops!"));
    logger.log(Level.SEVERE, "", new Exception("Boom!"));
    logger.log(Level.WARNING, "Unable to do that, falling back...");
    logger.log(Level.INFO, "Hello!");
  }
}
```

With the above definition, you get the following output in stderr:

```
Something went wrong :(
java.lang.Exception: Ooops!
	at com.plantuml.PlantumlLogger.main(PlantumlLogger.java:54)
java.lang.Exception: Boom!
	at com.plantuml.PlantumlLogger.main(PlantumlLogger.java:55)
Unable to do that, falling back...
Hello!
```

I believe this is what we get using `printStackTrace`?

The main benefit is that we can now bridge the logger to slf4j using `jul-to-slf4j`. In the following example, I'm using slf4j with Logback:

```java
// bridge PlantUML logger to SLF4J
Logger plantumlLogger = LogManager.getLogManager().getLogger("com.plantuml");
Handler[] handlers = plantumlLogger.getHandlers();
for (Handler existingHandler : handlers) {
  plantumlLogger.removeHandler(existingHandler);
}
plantumlLogger.addHandler(new SLF4JBridgeHandler());
```

And now I get the following output in stdout:

```
11:23:21.884 [main] ERROR com.plantuml - Something went wrong :(
java.lang.Exception: Ooops!
	at com.plantuml.PlantumlLogger.main(PlantumlLogger.java:52)
11:23:21.886 [main] ERROR com.plantuml - 
java.lang.Exception: Boom!
	at com.plantuml.PlantumlLogger.main(PlantumlLogger.java:53)
11:23:21.887 [main] WARN  com.plantuml - Unable to do that, falling back...
11:23:21.887 [main] INFO  com.plantuml - Hello!
```

What do you think?

**Comment by arnaudroques** [comment]
> What do you think?

We can give a try :-)

Could you put the classes you will create in a new package `net.sourceforge.plantuml.log` ?
