### ISSUE TITLE
NullPointerException when using `-ttxt` or `-tutxt` with some deployment diagrams

### ISSUE THREAD

**Issue by jeandeaual** [plantuml/plantuml#1117]
I understand that [ASCII art output](https://plantuml.com/ascii-art) is mostly made for sequence diagrams, but it also seems to produce some output for most other diagram types.

However, I encountered an exception with the following example:

```plantuml
@startuml

actor User as user

package Package as a {
  agent Agent as agent_a
}

package Package as b {
  agent Agent as agent_b
}

user -u-> agent_a : Query
user -u-> agent_b : Query

note as n
  Note
end note

n .. b

@enduml
```

With `-ttxt` or `-tutxt`, this generates a text file with the following contents:

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at net.sourceforge.plantuml.posimo.Path.<init>(Path.java:59)
	at net.sourceforge.plantuml.cucadiagram.dot.CucaDiagramTxtMaker.<init>(CucaDiagramTxtMaker.java:114)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.createFilesTxt(CucaDiagram.java:634)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:579)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:135)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:180)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:518)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:401)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:368)
	at net.sourceforge.plantuml.Run.main(Run.java:203)
```

See it [here](http://www.plantuml.com/plantuml/txt/TO-z3G8n58DxJ-45xWQWGCS220fgz794540E9Iy5GkoEmmyDqCInFzbHXkAMlPwEW8q-PMvApBJ2AWNEDXvi7xbwgO3n2b8cEHVjLFYqMyFjPoNyhuHMQM-ngztylSCPrpNconS97u8q-MCyWLpgZfXsRA4G-vu161JfQtS0) on PlantUML server.

Removing any element from this diagram produces an output with no exception.

Here's my configuration:

```
plantuml -version
PlantUML version 1.2022.7 (Tue Aug 23 02:01:30 JST 2022)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 5.0.1 (20220820.1526)
Installation seems OK. File generation OK
```

**Comment by DrPepperBianco** [comment]
I have the same problem. Can’t output my diagrams as text.

**Comment by Otto-AA** [comment]
I encountered a similar NPE with a simple component diagram:

```plantuml
@startuml
database X {
  [Y]
}

X -- Z
@enduml
```

Here is the ASCII link: https://www.plantuml.com/plantuml/txt/SoWkIImgAStDuKf9B4bCIYnELOXGgEPIK8YEZEMgvUAAKD3LLOZYSaZDIm4g0W00
