### ISSUE TITLE
Improve jar start up time

### ISSUE THREAD

**Issue by dylan-chong** [plantuml/plantuml#123]
```
> time plantuml nonexistentfile

real    0m5.827s
user    0m2.131s
sys     0m0.464s
```

The start-up time is ridiculously long. The example below shows how long it takes before Plant UML realises that the given file argument doesn't actually exist.

Six seconds to do nothing is far too long! This is definitely a problem for plug-ins such as the one mentioned in [my comment here](https://github.com/plantuml/plantuml/issues/122#issuecomment-390379648) because it takes an additional six seconds to export the file.

It would be awesome if the load time could be greatly reduced.

**Comment by dylan-chong** [comment]
The most significant slow part is this https://github.com/dylan-chong/plantuml/blob/test/slow-loading/src/net/sourceforge/plantuml/Run.java#L215

**Comment by arnaudroques** [comment]
Some users had some issues running PlantUML with OpenJDK (process was hanging).
We figure out that on OpenJDK we have to force some resource initilization to let the process run normally. I have no idea why OpenJDK need this...
On our Oracle JVM, forceOpenJdkResourceLoad() was running without issues.

BTW, which Java JVM are you using ? It looks like you are using a Oracle JVM.
Could you post here the result of:
```
@startuml
version
@enduml
```

What we can do, is to test in the Java code which JVM is used and call forceOpenJdkResourceLoad() only is the underlaying JVM is OpenJDK.

**Comment by dylan-chong** [comment]
> ```
> @startuml
> version
> @enduml
> ```

<img width="545" alt="screen shot 2018-05-20 at 1 03 30 pm" src="https://user-images.githubusercontent.com/17482349/40274587-4cf69bf2-5c2e-11e8-9e2e-5b87ef1f12a1.png">

**Comment by arnaudroques** [comment]
Ok, thanks.
We've added this test in V1.2018.6
https://github.com/plantuml/plantuml/blob/d7ecae5722455af80658472b1b4e15e2c865bae3/src/net/sourceforge/plantuml/Run.java#L198

I'm still interested in your tests. I don't understand why option management is so long:
`1 options           : 1102 ms
`
Note that you can add `-verbose` flag at plantuml command line to have some more timing information.
Thanks for your feedback

**Comment by wolfch** [comment]
This is is throwing `NullPointerException` for me.  Not only the "version" test, above, but _any_ diagram.

```
$ java -jar /opt/lib/plantuml.1.2019.13.jar -v version.puml
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2019.13
(0.004 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false
(0.004 - 245 Mo) 237 Mo - Forcing resource load on OpenJdk
Exception in thread "main" java.lang.NullPointerException
	at sun.font.FontDesignMetrics.getDefaultFrc(FontDesignMetrics.java:157)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:278)
	at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863)
	at net.sourceforge.plantuml.Run.forceOpenJdkResourceLoad(Run.java:236)
	at net.sourceforge.plantuml.Run.main(Run.java:143)
```

```
$ java -jar /opt/lib/plantuml.1.2019.13.jar -version
PlantUML version 1.2019.13 (Tue Dec 10 12:18:29 EST 2019)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Java Version: 1.8.0_232-b09
Operating System: Mac OS X
Default Encoding: UTF-8
Language: en
Country: US
Machine: ELSPHIM-223046
PLANTUML_LIMIT_SIZE: 4096
Processors: 12
Max Memory: 3,817,865,216
Total Memory: 257,425,408
Free Memory: 249,044,712
Used Memory: 8,380,696
Thread Active Count: 1

The environment variable GRAPHVIZ_DOT has not been set
Dot executable is /usr/local/bin/dot
Dot version: dot - graphviz version 2.43.0 (0)
Installation seems OK. File generation OK
```

**Comment by wolfch** [comment]
To add to my comment, above - I just tried adding the option `-headless` and now, no `NullPointerException`!  ...but I never had to do that before.

```
$ java -jar /opt/lib/plantuml.1.2019.13.jar -headless -v version.puml
(0.000 - 245 Mo) 238 Mo - PlantUML Version 1.2019.13
(0.001 - 245 Mo) 238 Mo - GraphicsEnvironment.isHeadless() true
(0.001 - 245 Mo) 238 Mo - Forcing -Djava.awt.headless=true
(0.001 - 245 Mo) 238 Mo - java.awt.headless set as true
(0.002 - 245 Mo) 238 Mo - Forcing resource load on OpenJdk
(0.825 - 245 Mo) 237 Mo - Found 1 files
(0.825 - 245 Mo) 237 Mo - Working on /Users/ma-wolf2/Documents/version.puml
(0.836 - 245 Mo) 237 Mo - Setting current dir: .
(0.836 - 245 Mo) 237 Mo - Setting current dir: /Users/ma-wolf2/Documents
(0.836 - 245 Mo) 237 Mo - Using default charset
(0.843 - 245 Mo) 237 Mo - Reading from version.puml
(0.874 - 245 Mo) 236 Mo - Reading file: version.puml
(1.080 - 245 Mo) 219 Mo - Starting Graphviz process [/usr/local/bin/dot, -Tsvg]
(1.080 - 245 Mo) 219 Mo - DotString size: 21
(1.100 - 245 Mo) 217 Mo - Ending process ok
(1.100 - 245 Mo) 217 Mo - Ending Graphviz process
(1.134 - 245 Mo) 217 Mo - Compilation duration 251
(1.134 - 245 Mo) 217 Mo - Regex total/invoked/compiled 176/171/58
(1.134 - 245 Mo) 217 Mo - Matches created 0
(1.136 - 245 Mo) 217 Mo - Creating file: /Users/ma-wolf2/Documents/version.png
(1.231 - 245 Mo) 192 Mo - Creating image 489x344
(1.284 - 245 Mo) 218 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.333 - 245 Mo) 217 Mo - Number of image(s): 1
```

**Comment by soloturn** [comment]
this should be closed, current behavior is, on arch with openjdk-18:

```
> time plantuml nonex
No diagram found

________________________________________________________
Executed in  348.36 millis    fish           external
   usr time  417.82 millis    1.00 millis  416.82 millis
   sys time   79.15 millis    0.25 millis   78.90 millis


> time plantuml -v version.puml
(0.000 - 248 Mo) 243 Mo - SecurityProfile LEGACY
(0.007 - 248 Mo) 243 Mo - PlantUML Version 1.2022.6
(0.007 - 248 Mo) 243 Mo - GraphicsEnvironment.isHeadless() false
(0.008 - 248 Mo) 243 Mo - Forcing resource load on OpenJdk
(0.073 - 248 Mo) 242 Mo - Found 0 files
No diagram found

________________________________________________________
Executed in  315.39 millis    fish           external
   usr time  491.81 millis   38.14 millis  453.67 millis
   sys time   46.01 millis   16.28 millis   29.74 millis

```
