### ISSUE TITLE
Stack trace with `@starthcl`

### ISSUE THREAD

**Issue by albert-github** [plantuml/plantuml#1279]
In the question https://forum.plantuml.net/17357/documentation-of-hcl-and-regex some information was asked and given abopout the HCL possibilities.
When trying a bit more complicated example from a page like https://hcl.readthedocs.io/en/latest/language_design.html I got always a stack dump even though I'm using : PlantUML version 1.2023.1 (Sun Jan 29 13:58:56 CET 2023).
The example:
```
@starthcl
{
io_mode = "async"

service "http" "web_proxy" {
  listen_addr = "127.0.0.1:8080"

  process "main" {
    command = ["/usr/local/bin/awesome-app", "server"]
  }

  process "mgmt" {
    command = ["/usr/local/bin/awesome-app", "mgmt"]
  }
}}
@endhcl
```

the stack trace:
```
java.lang.IllegalStateException: STRING_SIMPLE(service)
        at net.sourceforge.plantuml.hcl.HclParser.getBracketData(HclParser.java:133)
        at net.sourceforge.plantuml.hcl.HclParser.getModuleOrSomething(HclParser.java:86)
        at net.sourceforge.plantuml.hcl.HclParser.parseMe(HclParser.java:65)
        at net.sourceforge.plantuml.hcl.HclDiagramFactory.createSystem(HclDiagramFactory.java:78)
        at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:140)
        at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:181)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:168)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:519)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:402)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:369)
        at net.sourceforge.plantuml.Run.main(Run.java:204)
```

**Comment by arnaudroques** [comment]
Sorry, HCL implementation is really primary and is basically not working.
We will make it works someday but not on short term.
Please be patient :-)

**Comment by arnaudroques** [comment]
Your issue is now part of the official [backlog](https://github.com/orgs/plantuml/projects/4). 
For technical reason, it has been put at `close` state but it's really still open for us.
You can by the way go on and put any comment in this issue.

The main reason why we put this issue in the backlog is that we try to group issues together so that we fix them together, as similar issues often impact the same code area.

Please be patient, but stay tuned! 🙂
