### ISSUE TITLE
Unable to generate XMI output.

### ISSUE THREAD

**Issue by DarkStar1** [plantuml/plantuml#1493]
**Describe the bug**
It is currently not possible to generate XMI output from model document.

**To Reproduce**

1. Create UML entity relation diagram (ERD).
2. [Download](https://github.com/plantuml/plantuml/releases/tag/v1.2023.10) the plantUML jar (plantuml-1.2023.10.jar).
3. Convert UML document to xmi output by executing command in the command line: `java -jar ~/download/location/of/plantuml.jar erd-model.puml -txmi -o name-of-dir`
4. Throws error:
```
Exception in thread "main" java.lang.UnsupportedOperationException: XMI_STANDARD
	at net.atmp.ImageBuilder.createUGraphic(ImageBuilder.java:469)
	at net.atmp.ImageBuilder.writeImageInternal(ImageBuilder.java:296)
	at net.atmp.ImageBuilder.write(ImageBuilder.java:256)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:204)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:160)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:153)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:198)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:207)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:96)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:190)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:510)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:404)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:371)
	at net.sourceforge.plantuml.Run.main(Run.java:206)
```

**Expected behavior**
An XMI document is generated.

**Desktop (please complete the following information):**

- OS [MacOS 12.6.5 (Monterey)]
- JDK: [OpenJDK 64-Bit Server VM Homebrew]
- Version [build 11.0.19+0, mixed mode]

**Additional context**

**Comment by dgutson** [comment]
I have the same issue.
sample input file:
```plantuml
@startuml

A -> B
activate B

loop X
  C -> D
end
deactivate B

@enduml
```

Output:
```
Exception in thread "main" java.lang.UnsupportedOperationException: XMI_STANDARD
        at net.atmp.ImageBuilder.createUGraphic(ImageBuilder.java:469)
        at net.atmp.ImageBuilder.writeImageInternal(ImageBuilder.java:296)
        at net.atmp.ImageBuilder.write(ImageBuilder.java:256)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:204)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:160)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:153)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:207)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsSequence(PSystemUtils.java:153)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:89)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:190)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:510)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:404)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:371)
        at net.sourceforge.plantuml.Run.main(Run.java:206)
```

output of -v:
```
daniel@ECL-SAMSUNG-LT-GDaniel:~/src/architecture$ java -jar plantuml.jar -v
(0.001 - 124 Mo) 118 Mo - SecurityProfile LEGACY
(0.012 - 124 Mo) 118 Mo - PlantUML Version 1.2023.11
(0.012 - 124 Mo) 118 Mo - GraphicsEnvironment.isHeadless() false
(0.013 - 124 Mo) 118 Mo - Forcing resource load on OpenJdk
```
