### ISSUE TITLE
Ditaa no longer activated in ASL build

### ISSUE THREAD

**Issue by pepijnve** [plantuml/plantuml#1514]
**Describe the bug**
The ASL licensed build of PlantUML no longer activates Ditaa support.

**To Reproduce**

1. Download the artefact `net.sourceforge.plantuml:plantuml-asl:1.2023.10` from the maven central repo.
2. Try to process a ditaa diagram from the CLI
3. The following error is reported

```
... ~ % java -jar plantuml-asl-1.2023.10.jar test.ditaa
java.lang.IllegalStateException
	at net.sourceforge.plantuml.error.PSystemErrorUtils.merge(PSystemErrorUtils.java:25)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:117)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:152)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:137)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:476)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:370)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:337)
	at net.sourceforge.plantuml.Run.main(Run.java:172)
Exception in thread "main" java.lang.IllegalStateException
	at net.sourceforge.plantuml.error.PSystemErrorUtils.merge(PSystemErrorUtils.java:25)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:117)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:152)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:485)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:370)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:337)
	at net.sourceforge.plantuml.Run.main(Run.java:172)
```

**Expected behavior**
~Based on the preprocessor directive at https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/PSystemBuilder.java#L212 Ditaa support should be available in the ASL licensed build.~
I misread the directive. Expected behaviour was that this worked though since it used to work in earlier versions of the ASL distribution.

**Desktop (please complete the following information):**

- OS: macOS 13.5 (but not relevant)
- Browser: not relevant
- Version: not relevant

**Comment by arnaudroques** [comment]
I think that ditaa code is distributed under GPL license.
Since ASL and GPL licenses are incompatible (well, I think so), it is not possible to have Ditaa support in ASL licensed build.

So previous versions were not correct.
Really sorry about that!

**Comment by pepijnve** [comment]
Ok that makes sense. I checked just to be sure. Ditaa is LGPLv3 licensed (see https://github.com/stathissideris/ditaa/blob/master/LICENSE). Would it be ok to remove the LGPL case from https://github.com/plantuml/plantuml/blob/master/src/net/sourceforge/plantuml/PSystemBuilder.java#L211?

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @pepijnve for the report.
- Thanks PlantUML team for your work.

Regards.
