### ISSUE TITLE
Build fails on Alpine Linux aarch64

### ISSUE THREAD

**Issue by chereskata** [plantuml/plantuml#1543]
**Describe the bug**
Building Plantuml on aarch64 (gitlab CI) does segfault the JVM. (openjdk17). I have have also tried java8 (openjdk8) but the effect is identical.

**To Reproduce**
(Install Alpine Linux aarch64 - have not tested on other distro)
1. `git clone https://gitlab.alpinelinux.org/chereskata/aports/-/tree/plantuml` (https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package)
2. `cd aports/community/plantuml/`
3. `sed -e "s/!aarch64//" -i APKBUILD` 
4. `abuild -rK`

**Expected behavior**
Build without issues

**Logs**
```
Process command line: /usr/lib/jvm/java-17-openjdk/bin/java --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /builds/chereskata/aports/community/plantuml/src/.gradle/wrapper/dists/gradle-8.2-bin/bbg7u40eoinfdyxsxr3z4i7ta/gradle-8.2/lib/gradle-launcher-8.2.jar -javaagent:/builds/chereskata/aports/community/plantuml/src/.gradle/wrapper/dists/gradle-8.2-bin/bbg7u40eoinfdyxsxr3z4i7ta/gradle-8.2/lib/agents/gradle-instrumentation-agent-8.2.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.2
Please read the following process output to find out more:
-----------------------
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000000002b1c0, pid=410, tid=412
#
# JRE version: OpenJDK Runtime Environment (17.0.8+7) (build 17.0.8+7-alpine-r2)
# Java VM: OpenJDK 64-Bit Server VM (17.0.8+7-alpine-r2, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)
# Problematic frame:
# C  [libnative-platform-file-events.so+0x2eb8c]  _init+0x39e4
#
# Core dump will be written. Default location: /builds/chereskata/aports/community/plantuml/src/.gradle/daemon/8.2/core
#
# An error report file with more information is saved as:
# /builds/chereskata/aports/community/plantuml/src/.gradle/daemon/8.2/hs_err_pid410.log
#
# If you would like to submit a bug report, please visit:
#   https://gitlab.alpinelinux.org/alpine/aports/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
	at org.gradle.launcher.daemon.client.DaemonGreeter.parseDaemonOutput(DaemonGreeter.java:38)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startProcess(DefaultDaemonStarter.java:195)
	at org.gradle.launcher.daemon.client.DefaultDaemonStarter.startDaemon(DefaultDaemonStarter.java:151)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.doStartDaemon(DefaultDaemonConnector.java:222)
	at org.gradle.launcher.daemon.client.DefaultDaemonConnector.startSingleUseDaemon(DefaultDaemonConnector.java:247)
	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:51)
	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:57)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:167)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:259)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$ParseAndBuildAction.execute(DefaultCommandLineActionFactory.java:230)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:74)
	at org.gradle.launcher.cli.DebugLoggerWarningAction.execute(DebugLoggerWarningAction.java:30)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:96)
	at org.gradle.launcher.cli.WelcomeMessageAction.execute(WelcomeMessageAction.java:40)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:44)
	at org.gradle.launcher.cli.NativeServicesInitializingAction.execute(NativeServicesInitializingAction.java:26)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:41)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:26)
	at org.gradle.launcher.cli.DefaultCommandLineActionFactory$WithLogging.execute(DefaultCommandLineActionFactory.java:361)
	at org.gradle.launcher.Main.doAction(Main.java:35)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:50)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:35)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
>>> ERROR: plantuml: build failed

```

**Additional infos:**
- OS: Alpine Linux edge

**Comment by soloturn** [comment]
@bratkartoffel is this same with gradle-8.3 and java-21 ?

**Comment by bratkartoffel** [comment]
Issue still persists: https://tpaste.us/ePYV

**Comment by bratkartoffel** [comment]
see https://github.com/gradle/gradle/issues/24875#issuecomment-1732492926

**Comment by webark** [comment]
not sure if this is related, but there is no version for aarch64 for 3.19. https://pkgs.alpinelinux.org/packages?name=plantuml&branch=v3.19&repo=&arch=&maintainer= There is one for 3.18 however.

**Comment by webark** [comment]
does anyone know what the process is for publishing the `aarch64` for Alpine Edge and 3.19 or later?

**Comment by webark** [comment]
🤦‍♂️ course.. Yes. That makes sense. Thanks!

**Comment by webark** [comment]
@bratkartoffel That bug appears to be somewhat fixed. (it's closed as fixed at least) I could try testing it out tomorrow if it's something somewhat straightforward to do..? 🤷‍♂️

**Comment by bratkartoffel** [comment]
Afaik the issue is fixed, but waits for the next release, 8.8

Am 9. April 2024 04:47:33 UTC schrieb Mark Avery ***@***.***>:

**Comment by webark** [comment]
Sorry for my lack of patience!! 🫣

**Comment by bratkartoffel** [comment]
Don't worry, i will test it and keep you updated as soon as he gradle release is out

**Comment by webark** [comment]
Did the grade fix ever get out?

**Comment by bratkartoffel** [comment]
Yes, and I totally forgot about this issue.
I've filed a merge request on alpine, so plantuml should be available as soon as it gets merged.

- edge: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/68683
- 3.20: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/68684

Nevertheless plantuml should "officially" upgrade the wrapper.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed.
- Thanks @chereskata  for the report.
- Thanks @bratkartoffel for your work.

Regards.
