### ISSUE TITLE
Crash on sample DITAA diagram

### ISSUE THREAD

**Issue by veselov** [plantuml/plantuml#1582]
Input:
```puml
@startditaa
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
    :                         ^
    |       Lots of work      |
    +-------------------------+
@endditaa
```

Running:
```
[vps@hornet]~$ /usr/lib/jvm/jre-11/bin/java -jar ~/Downloads/plantuml-mit-1.2023.11.jar scratch_138.puml 
java.lang.IllegalStateException
	at net.sourceforge.plantuml.error.PSystemErrorUtils.merge(PSystemErrorUtils.java:98)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:199)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:225)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:210)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:549)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:443)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:410)
	at net.sourceforge.plantuml.Run.main(Run.java:245)
Exception in thread "main" java.lang.IllegalStateException
	at net.sourceforge.plantuml.error.PSystemErrorUtils.merge(PSystemErrorUtils.java:98)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:199)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:225)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:558)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:443)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:410)
	at net.sourceforge.plantuml.Run.main(Run.java:245)
```

Rendering output:
![scratch_138](https://github.com/plantuml/plantuml/assets/2555513/497f7ab3-3604-493d-be12-f119974ff862)

**Comment by The-Lum** [comment]
Hi all,

It is due to licence: `ditaa` is disabled on MIT version.

See similar issue here:
- #1514

Regards,
Th.

**Comment by veselov** [comment]
I would request that the exception has a better message, and https://plantuml.com/download has information about components not being available in specific distributions.

**Comment by arnaudroques** [comment]
Many thanks @The-Lum for the idea on [the download page](https://plantuml.com/download).
Release 1.2023.12 should print a better message, probably not perfect though.
You can try and tell us what you think about it!
