### ISSUE TITLE
ELK Layout Crashes

### ISSUE THREAD

**Issue by rowhit** [plantuml/plantuml#1633]
**Describe the bug**
I am trying to run the example provided on "https://plantuml.com/component-diagram":

```
@startuml
!pragma layout elk

[c]
component C {
  port p1
  port p2
  port p3
  component c1
}

c --> p1
c --> p2
c --> p3
p1 --> c1
p2 --> c1
@enduml
```
However, it fails with the following if I try to use ELK layout. Apparently, other ELK examples works fine and this program seems to occur only for the case with components having ports (therefore, I do not suspect any installation issue) . Also, to confirm that default layout engine works fine.

I am running the file with following command (with elk-full.jar present in the same dir)
```
java -jar plantuml-SNAPSHOT.jar -tsvg  elk_example__component.svg elk_example__component.puml
```

The error I get is following:
```
java.lang.NullPointerException
        at net.sourceforge.plantuml.svek.image.EntityImagePort.upPosition(EntityImagePort.java:122)
        at net.sourceforge.plantuml.svek.image.EntityImagePort.drawU(EntityImagePort.java:149)
        at net.sourceforge.plantuml.elk.CucaDiagramFileMakerElk$Drawing.drawSingleNode(CucaDiagramFileMakerElk.java:372)
        at net.sourceforge.plantuml.elk.CucaDiagramFileMakerElk$Drawing.drawAllNodes(CucaDiagramFileMakerElk.java:306)
        at net.sourceforge.plantuml.elk.CucaDiagramFileMakerElk$Drawing.drawU(CucaDiagramFileMakerElk.java:294)
        at net.sourceforge.plantuml.klimt.shape.TextBlockUtils.getMinMax(TextBlockUtils.java:189)
        at net.sourceforge.plantuml.elk.CucaDiagramFileMakerElk.createFile(CucaDiagramFileMakerElk.java:439)
        at net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:477)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:181)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:250)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:248)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:138)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:234)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:554)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:448)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:415)
        at net.sourceforge.plantuml.Run.main(Run.java:250)
```
I have installed the elk-full.jar along with plantuml.jar (including the latest release, have tried earlier versions too but same result), even tried to build from scratch both ELK and pantuml but the problem.

**To Reproduce**
Steps are described above.

**Expected behavior**
The expected output is a component diagram with ELK layout

**Desktop (please complete the following information):**
- OS: ubuntu 20.04
- Browser: Firefox
- Version: 121.0

**Comment by rowhit** [comment]
A similar issue is occuring with the "smetana" layout engine as well. In this case, I get the following:

```
java.lang.NullPointerException
        at net.sourceforge.plantuml.klimt.geom.ClusterPosition.merge(ClusterPosition.java:75)
        at net.sourceforge.plantuml.svek.FrontierCalculator.<init>(FrontierCalculator.java:57)
        at net.sourceforge.plantuml.svek.Cluster.manageEntryExitPoint(Cluster.java:385)
        at net.sourceforge.plantuml.svek.Cluster.drawU(Cluster.java:319)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana.drawGroup(CucaDiagramFileMakerSmetana.java:238)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana.access$2(CucaDiagramFileMakerSmetana.java:218)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana$Drawing.drawU(CucaDiagramFileMakerSmetana.java:165)
        at net.atmp.ImageBuilder.getFinalDimension(ImageBuilder.java:358)
        at net.atmp.ImageBuilder.writeImageInternal(ImageBuilder.java:280)
        at net.atmp.ImageBuilder.write(ImageBuilder.java:257)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana.createFileLocked(CucaDiagramFileMakerSmetana.java:378)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana.createFile(CucaDiagramFileMakerSmetana.java:347)
        at net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:445)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:141)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:187)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:206)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:95)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:189)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:524)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:407)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:374)
        at net.sourceforge.plantuml.Run.main(Run.java:208)
```

**Comment by The-Lum** [comment]
_[Just for the record]_

See also pseudo-similar issue here:
- https://github.com/plantuml/plantuml/issues/1441

Regards,
Th.
