### ISSUE TITLE
UnsupportedOperationException at latex output and interfaces )--

### ISSUE THREAD

**Issue by koppor** [plantuml/plantuml#178]
PlantUML Version 1.2019.02

Interfaces seem not to be fully supported by the LaTeX output. Minimal file:

```
@startuml
I2 )-- c2
@enduml
```

I run following command

    java -jar C:\ProgramData\chocolatey\lib\plantuml\tools\plantuml.jar -tlatex min.plantuml.txt

Output:

```
java.lang.UnsupportedOperationException
        at net.sourceforge.plantuml.ugraphic.tikz.DriverEllipseTikz.draw(DriverEllipseTikz.java:61)
        at net.sourceforge.plantuml.ugraphic.tikz.DriverEllipseTikz.draw(DriverEllipseTikz.java:44)
        at net.sourceforge.plantuml.ugraphic.AbstractUGraphic.draw(AbstractUGraphic.java:89)
        at net.sourceforge.plantuml.svek.extremity.ExtremityParenthesis.drawU(ExtremityParenthesis.java:67)
        at net.sourceforge.plantuml.svek.Line.drawRainbow(Line.java:758)
        at net.sourceforge.plantuml.svek.Line.drawU(Line.java:704)
        at net.sourceforge.plantuml.svek.SvekResult.drawU(SvekResult.java:92)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:254)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:178)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:127)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:71)
        at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:379)
        at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:193)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:248)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsCuca(PSystemUtils.java:236)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:92)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:157)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:508)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:403)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:372)
        at net.sourceforge.plantuml.Run.main(Run.java:188)
```

**Comment by arnaudroques** [comment]
Thanks for the report.
We've made a quick fix in last beta http://beta.plantuml.net/plantuml.jar

Maybe it's not working in all cases : tell us if you find other issues!
Regards,

**Comment by koppor** [comment]
Works. Thank you for the quick action taken.
