### ISSUE TITLE
pdf support broken with other gradle build file changes

### ISSUE THREAD

**Issue by matthewberryman** [plantuml/plantuml#1850]
**Describe the bug**
Building the JAR file with PDF support broken since aeef84479ab9cd567f051ff7cd718565bbbe2f57

**To Reproduce**
Steps to reproduce the behaviour:
Run `gradle pdfJar`
```
matthew@MacBookPro ~/c/plantuml ((aeef8447)|BISECTING)> java -jar build/libs/plantuml-pdf-1.2024.6beta8.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:340)
        at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:282)
        at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:276)
        at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:232)
        at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:760)
        at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1070)
        at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:42)
        at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:852)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:848)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:534)
        at java.base/java.lang.Class.forName(Class.java:513)
        at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:797)
        at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:692)
```

**Expected behavior**
valid, working JAR file

**Screenshots**
N/A

**Desktop (please complete the following information):**

- OS: macOS 15 beta 2
- Browser: not relevant, using the CLI to run

```
matthew@MacBookPro ~/c/plantuml ((aeef8447)|BISECTING)> java --version
openjdk 21.0.3 2024-04-16 LTS
OpenJDK Runtime Environment Corretto-21.0.3.9.1 (build 21.0.3+9-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.3.9.1 (build 21.0.3+9-LTS, mixed mode, sharing)

matthew@MacBookPro ~/c/plantuml ((aeef8447)|BISECTING)> gradle --version

------------------------------------------------------------
Gradle 8.8
------------------------------------------------------------

Build time:   2024-05-31 21:46:56 UTC
Revision:     4bd1b3d3fc3f31db5a26eecb416a165b8cc36082

Kotlin:       1.9.22
Groovy:       3.0.21
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          22.0.1 (Homebrew 22.0.1)
OS:           Mac OS X 15.0 aarch64
```

**Smartphone (please complete the following information):**
not relevant

**Comment by The-Lum** [comment]
_[Just for the record]_
Fixed by:
- #1851 

_Thanks for your works._
Regards,
Th.
