### ISSUE TITLE
Activity diagram input split (multi-start) doesn't work with EPS output

### ISSUE THREAD

**Issue by cpacejo** [plantuml/plantuml#1889]
**Describe the bug**
Activity diagram input split (multi-start) doesn't work with EPS output.

**To Reproduce**
Using the example from the manual:
```
@startuml
split
   -[hidden]->
   :A;
split again
   -[hidden]->
   :B;
split again
   -[hidden]->
   :C;
end split
:D;
@enduml
```

`plantuml -teps <input>` produces an EPS file with a Java backtrace, starting with a `java.lang.IllegalStateException`.

PNG and SVG backends work as expected.

**Expected behavior**
A diagram should be produced.

**Screenshots**
![bug-eps](https://github.com/user-attachments/assets/ec388f08-17da-4ec3-b114-552f726a1204)

**Desktop (please complete the following information):**

- OS: Debian GNU/Linux 12 (bookworm)
- Browser N/A
- Version 1.2024.6

**Comment by modem7** [comment]
I am also experiencing this issue.

```
java.lang.IllegalStateException
 at net.sourceforge.plantuml.klimt.drawing.eps.EpsGraphics.epsLine(EpsGraphics.java:237)
 at net.sourceforge.plantuml.klimt.drawing.eps.DriverLineEps.draw(DriverLineEps.java:73)
 at net.sourceforge.plantuml.klimt.drawing.eps.DriverLineEps.draw(DriverLineEps.java:46)
 at net.sourceforge.plantuml.klimt.drawing.AbstractUGraphic.draw(AbstractUGraphic.java:144)
 at net.sourceforge.plantuml.klimt.drawing.AbstractUGraphicHorizontalLine.draw(AbstractUGraphicHorizontalLine.java:77)
 at net.sourceforge.plantuml.klimt.creole.atom.AtomTable.drawU(AtomTable.java:149)
 at net.sourceforge.plantuml.klimt.creole.atom.AtomWithMargin.drawU(AtomWithMargin.java:64)
 at net.sourceforge.plantuml.klimt.creole.SheetBlock1.drawU(SheetBlock1.java:204)
 at net.sourceforge.plantuml.klimt.creole.SheetBlock2.drawU(SheetBlock2.java:103)
 at net.sourceforge.plantuml.klimt.shape.TextBlockBordered.drawU(TextBlockBordered.java:141)
 at net.sourceforge.plantuml.klimt.shape.TextBlockMarged.drawU(TextBlockMarged.java:83)
 at net.sourceforge.plantuml.svek.DecorateEntityImage.drawU(DecorateEntityImage.java:130)
 at net.sourceforge.plantuml.svek.DecorateEntityImage.drawU(DecorateEntityImage.java:123)
 at net.atmp.ImageBuilder.writeImageInternal(ImageBuilder.java:275)
 at net.atmp.ImageBuilder.write(ImageBuilder.java:239)
 at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:142)
 at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:70)
 at net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:489)
 at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:119)
 at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:220)
 at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:210)
 at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:98)
 at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:197)
 at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:344)
 at net.sourceforge.plantuml.Run.lambda$processInputsInParallel$12(Run.java:301)
 at net.sourceforge.plantuml.Run.lambda$processInParallel$14(Run.java:317)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 at java.base/java.lang.Thread.run(Thread.java:1583)
```
