### ISSUE TITLE
Fedora 41 using wayland and completely removing x11

### ISSUE THREAD

**Issue by chahidanas** [plantuml/plantuml#1975]
Since switching to Fedora 41 I'm getting the headless error because Fedora completely removed X11

I think it would be nice to switch to wayland and ditch X11 since a lot of distros are going that way as well

**Comment by arnaudroques** [comment]
If you haven't tried it yet, you could experiment with running PlantUML in "headless" mode by adding the `-headless` flag. (see https://forum.plantuml.net/3399/problem-with-x11-and-headless-exception ) 

This setting can sometimes resolve rendering issues in environments without full display support (like when using Wayland or X11 alternatives). The headless mode in Java is designed to work without any display, which can bypass the need for X11 altogether for applications that don’t need a graphical interface.

**Comment by chahidanas** [comment]
Thank you for your answer, before I could try your workaround I've been trying to solve the issue and might stambled across the solution.

A default system have the following:
```
$ java -version
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.5.0.11-1) (build 21.0.5+11, mixed mode, sharing)
```
But none of the following:
```
package java-21-openjdk-devel is not installed
package libXaw is not installed
package libX11 is not installed
```
So after installing the following packages and their dependencies:
```
sudo dnf install java-21-openjdk-devel libXaw libX11
```
I got the following gui after running:
```
java -jar plantuml-1.2024.8.jar -gui
```
![plantuml](https://github.com/user-attachments/assets/ce0c9bef-b6b5-4eba-898e-890f7e5b344d)
![plantuml2](https://github.com/user-attachments/assets/1228f5b0-1ba9-4ba0-82ec-edcf6d397184)

Now I will just need a confirmation that this is the complete gui interface a normal installation would let the user to get.
If yes you can let me know and I will add a section in the README to help the users that encounter the same issue solve it.

PS: The diagram generation is working.
**Hope my contribution help new users that still aren't familiar with command lines or just prefer gui.**

**Comment by explode** [comment]
I recently upgraded to Ubuntu 25.10 (i.e. GNOME 49, Windowing system = Wayland).  Web search results suggest that Java does not support Wayland yet?  And GNOME 49 drops support for XWayland?  

Drawings will still render OK via the command line, but `-gui` interface is broken.  If I run:
    
    $ java   -jar plantuml-1.2026.5.jar   -verbose   -gui

The first GUI window appears OK (the one with a command button labelled CHANGE DIRECTORY) and lists PlantUML files discovered in target folder.  Double-clicking one of those items opens a second GUI window (the one with command buttons PREVIOUS, COPY, NEXT, etc)... but that window is empty, **no preview graphic renders**.  Its titlebar works OK (shows number of entities and updates when you edit the source file).  I also tried forcing JRE into headless mode, but that fails:

	$ java   -Djava.awt.headless=true   -jar plantuml-1.2026.5.jar   -verbose   -gui
	(0.200 - 126 Mo) 116 Mo - SecurityProfile LEGACY
	(0.218 - 126 Mo) 115 Mo - PlantUML Version 1.2026.5
	(0.220 - 126 Mo) 115 Mo - GraphicsEnvironment.isHeadless() true
	(0.220 - 126 Mo) 115 Mo - Forcing resource load on OpenJdk
	There is an issue with your server. You will find some tips here:
	https://forum.plantuml.net/3399/problem-with-x11-and-headless-exception
	https://plantuml.com/en/faq#239d64f675c3e515
	Exception in thread "main" java.awt.HeadlessException
		at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:164)
		at java.desktop/java.awt.Window.<init>(Window.java:553)
		at java.desktop/java.awt.Frame.<init>(Frame.java:428)
		at java.desktop/javax.swing.JFrame.<init>(JFrame.java:224)
		at net.sourceforge.plantuml.swing.MainWindow.<init>(MainWindow.java:159)
		at net.sourceforge.plantuml.Run.runGui(Run.java:389)
		at net.sourceforge.plantuml.Run.main(Run.java:178)

Note the suggested URL in the help text is out-of-date - should be https://plantuml.com/en/faq#98ae26f36a6a06df.

Environment:

	$ plantuml --version
	PlantUML version 1.2026.5 / e0f0ce5 [2026-05-27 17:39:27 UTC]
	(GPL source distribution)

	Build Version: 1.2026.5
	Git Commit: e0f0ce5
	Compile Time: 2026-05-27 17:39:27 UTC

	Java Runtime: OpenJDK Runtime Environment
	JVM: OpenJDK 64-Bit Server VM
	Default Encoding: UTF-8
	Language: en
	Country: US

	PLANTUML_LIMIT_SIZE: 4096

	GraphViz: dot - graphviz version 2.42.4 (0)
	Installation seems OK. File generation OK

**Comment by arnaudroques** [comment]
Could you try with last snapshot?
I think this is the same issue as https://github.com/plantuml/plantuml/issues/2656 that has been fixed recently

**Comment by explode** [comment]
Downloaded latest snapshot from [here](https://github.com/plantuml/plantuml/releases) and `$ java -jar plantuml-gplv2-SNAPSHOT.jar -verbose -gui` works great.  Thanks and sorry I missed that other issue.  You're awesome.
