### ISSUE TITLE
[Skin] Allow (or skip) `skin` command on YAML diagram

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#1978]
Hello PlantUML Team,

## Context
To follow:
- PlantUML Theme/Skin Gallery construction.

## Wanted feature
- Could you allow `skin` on YAML diagram?
- _or skip..._

## Not working example :x:
```puml
@startyaml
skin plantuml
fruit: Apple
size: Large
color:
 - Red
 - Green
@endyaml
```
>[![](https://www.planttext.com/api/plantuml/svg/SoWkIImggKpCpU4gpixCKoZ8ISmhAGNoqefACqki51mB2d9IkOepgrAj57mIYz9JkPBpS_ABhBWKT1M2KbD0b7jHQceUbqDgNWh86000)](https://www.planttext.com/?text=SoWkIImggKpCpU4gpixCKoZ8ISmhAGNoqefACqki51mB2d9IkOepgrAj57mIYz9JkPBpS_ABhBWKT1M2KbD0b7jHQceUbqDgNWh86000) 

We observe an `UnsupportedOperationException`;
```js
java.lang.UnsupportedOperationException: skin plantuml
        at net.sourceforge.plantuml.yaml.SimpleYamlParser.parseSingleLine(SimpleYamlParser.java:112)
        at net.sourceforge.plantuml.yaml.SimpleYamlParser.parse(SimpleYamlParser.java:59)
        at net.sourceforge.plantuml.yaml.YamlDiagramFactory.createSystem(YamlDiagramFactory.java:85)
        at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:161)
        at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:188)
```

Regards,
Th.

**Comment by The-Lum** [comment]
Thanks.
That is fixed by:
- b15265e
