### ISSUE TITLE
Smetana throws an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by The-Lum** [plantuml/plantuml#2006]
## Context
To follow:
- https://forum.plantuml.net/19523/arrayindexoutofboundsexception-bounds-length-using-smetana

## Smetana throws an ArrayIndexOutOfBoundsException _(tested on 1.2024.9beta6)_
```js
java.lang.ArrayIndexOutOfBoundsException: Index 9 out of bounds for length 5
        at gen.lib.dotgen.mincross__c.left2right(mincross__c.java:367)
        at gen.lib.dotgen.mincross__c.transpose_step(mincross__c.java:520)
        at gen.lib.dotgen.mincross__c.transpose(mincross__c.java:569)
        at gen.lib.dotgen.mincross__c.build_ranks(mincross__c.java:1357)
        at gen.lib.dotgen.mincross__c.mincross_(mincross__c.java:599)
        at gen.lib.dotgen.mincross__c.dot_mincross(mincross__c.java:174)
        at gen.lib.dotgen.dotinit__c.dotLayout(dotinit__c.java:366)
        at gen.lib.dotgen.dotinit__c.doDot(dotinit__c.java:488)
        at gen.lib.dotgen.dotinit__c.dot_layout(dotinit__c.java:543)
        at gen.lib.dotgen.dotinit__c$2.exe(dotinit__c.java:535)
        at gen.lib.gvc.gvlayout__c.gvLayoutJobs(gvlayout__c.java:152)
        at net.sourceforge.plantuml.sdot.CucaDiagramFileMakerSmetana.getTextBlock(CucaDiagramFileMakerSmetana.java:475)
```

## Minimal not working example :x:
```puml
@startuml
!pragma layout smetana
!include <domainStory/domainStory>

System(Boarding, $note=^ above)
Person(person)
Info(thing1)
Info(thing2)
Info(thing3)

activity(1, person, reads, thing1, $note= default)
activity(2, person, reads, thing2, $note=^ above)
activity(3, person, reads, thing3, $note=> right)
activity(4, person, reads, Info: thing4, $note=v below)
activity(5, person, reads, Info: thing5, $note=~ inverse)
activity(6, person, reads, Info: thing6, $note=> right)
@enduml
```

Regards,
Th.

**Comment by The-Lum** [comment]
FYI @johthor
