### ISSUE TITLE
Crash when processing activity diagram

### ISSUE THREAD

**Issue by rbakhshi** [plantuml/plantuml#202]
I started getting this crash with this diagram. The expected output is an SVG but it generates an empty file.

If you comment out or remove the line that says "Removing this line will stop the crash!!!" it will generate the output.

# Diagram
```plantuml
@startuml

|A|


split
    :something;
split again
    :Removing this line will stop the crash!!!;
    
    |B|
    
    :a;
    repeat
        
        if(?) then (yes)
            split
                while (4 successful scans are not done?)
                    :a;
                    if(scanned successfully?) then (yes)
                        :a;
                    else
                        :a;
                    endif
                endwhile
            split again
                :a;
            end split
        endif
    repeat while(there is not enough fingers enrolled?)
end split

@enduml
```

# Error details:
```
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.sourceforge.plantuml.swing.MainWindow2.refreshDir(MainWindow2.java:372)
	at net.sourceforge.plantuml.swing.MainWindow2.access$600(MainWindow2.java:92)
	at net.sourceforge.plantuml.swing.MainWindow2$10.run(MainWindow2.java:338)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.StackOverflowError
	at java.util.HashMap.putVal(HashMap.java:628)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at net.sourceforge.plantuml.activitydiagram3.InstructionIf.getSwimlanes(InstructionIf.java:195)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes(InstructionList.java:157)
	at net.sourceforge.plantuml.activitydiagram3.Branch.getSwimlanes(Branch.java:116)
	at net.sourceforge.plantuml.activitydiagram3.InstructionIf.getSwimlanes(InstructionIf.java:198)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes(InstructionList.java:157)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlanes(InstructionSplit.java:127)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes(InstructionList.java:157)
	at net.sourceforge.plantuml.activitydiagram3.Branch.getSwimlanes(Branch.java:116)
	at net.sourceforge.plantuml.activitydiagram3.InstructionIf.getSwimlanes(InstructionIf.java:198)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes(InstructionList.java:157)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlanes(InstructionRepeat.java:157)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes2(InstructionList.java:187)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlanes(InstructionList.java:157)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:174)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(InstructionSplit.java:135)
	at net.sourceforge.plantuml.activitydiagram3.InstructionRepeat.getSwimlaneOut(InstructionRepeat.java:165)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.getSwimlaneOut(InstructionList.java:181)
	at net.sourceforge.plantuml.activitydiagram3.InstructionSplit.getSwimlaneOut(Instruct
```

# Command line used to run plantuml
```bash
java -DPLANTUML_LIMIT_SIZE=8192 -jar $(dirname $0)/plantuml-jar-mit-1.2019.5/plantuml.jar -tsvg -gui *.puml
```

**Comment by rbakhshi** [comment]
A workaround for it is wrapping the block which belongs to the second swim-lane (B) into an `if` block:

```
@startuml

|A|


split
    :something;
split again
    :Removing this line will stop the crash!!!;
    if(something useless?) then (yes)
        |B|
    
        :a;
        repeat
        
            if(?) then (yes)
                split
                    while (4 successful scans are not done?)
                        :a;
                        if(scanned successfully?) then (yes)
                            :a;
                        else
                            :a;
                        endif
                    endwhile
                split again
                    :a;
                end split
            endif
        repeat while(there is not enough fingers enrolled?)
    endif
end split

@enduml
```

**Comment by rbakhshi** [comment]
Also checked with the beta and this is also a bug in beta

**Comment by rbakhshi** [comment]
@arnaudroques unfortunately this is still happening even with the beta.
Same error for the same diagram.

**Comment by arnaudroques** [comment]
Could you check the beta version that you are currently using ?

```
@startuml
version
@enduml
```

Your initial example seems to work with beta16 and beta18 ( http://beta.plantuml.net/plantuml.jar )
Thanks!

**Comment by rbakhshi** [comment]
I am running beta 16:

```
PlantUML version 1.2019.06beta16(Unknown compile time)(GPL source distribution)Loaded from jar:file:/Users/user/bin/plantuml-beta-2019-05-08/plantuml.jar!
```

**Comment by rbakhshi** [comment]
Oh nice! Just downloaded beta 19 and it is fixed in this version!

Great Job! 👍
