### ISSUE TITLE
Crash at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)

### ISSUE THREAD

**Issue by Eluminae** [plantuml/plantuml#206]
Hello !

I got a problem without any reason (probably an upgrade but I'm not sure)

```
$ plantuml -ttxt XXX_XXX.uml 
java.io.IOException: Stream closed
        at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:442)
        at java.base/java.io.OutputStream.write(OutputStream.java:157)
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
        at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
        at java.base/java.io.FilterOutputStream.close(FilterOutputStream.java:182)
        at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:185)
        at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
        at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
```

The problem occurs with png too
![errored generated png](https://user-images.githubusercontent.com/14213590/58466491-098f8e00-813a-11e9-8fc9-35a10a0a6e0e.png)

```
$ plantuml -v
(0.000 - 188 Mo) 182 Mo - PlantUML Version 1.2019.05
(0.004 - 188 Mo) 182 Mo - GraphicsEnvironment.isHeadless() false
(0.004 - 188 Mo) 182 Mo - Forcing resource load on OpenJdk
(0.110 - 188 Mo) 177 Mo - Found 0 files
No diagram found
```

```
$ javac --version
javac 11.0.3
```

```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

```
$ uname -r
5.1.2-arch1-1-ARCH
```

What I'm missing ? Did I remove a dependency some time before by error ?

Ty by advance !
Kiss

**Comment by arnaudroques** [comment]
There is a an issue with your "dot" installation.
The message "Default dot version: unknown: -V usage: git...." is very strange. There should not be any connection with git here.
Could you try:
`dot -V`
on the command line.
And also:
```
@startuml
testdot
@enduml
```

**Comment by Eluminae** [comment]
```
$ dot -V
unknown option: -V
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

```
$ cat << EOF >> test.uml
$ @startuml
$ testdot
$ @enduml
$ EOF
eddie@laptop-ebarraco:~/tmp 11:38 
$ cat test.uml 
@startuml
testdot
@enduml
eddie@laptop-ebarraco:~/tmp 11:38 
$ plantuml -ttxt test.uml 
eddie@laptop-ebarraco:~/tmp 11:38 
$ cat test.atxt 
     The environment variable GRAPHVIZ_DOT has not been set                                                                                                                                                                                                                                                                                 
     Dot executable is /home/eddie/bin/dot                                                                                                                                                                                                                                                                                                  
     Dot version: unknown option: -V usage: git [version] [help] [-C <path>] [-c <name>=<value>]            [exec-path[=<path>]] [html-path] [man-path] [info-path]            [-p | paginate | -P | no-pager] [no-replace-objects] [bare]            [git-dir=<path>] [work-tree=<path>] [--namespace=<name>]            <command> [<args>]
     Warning : cannot determine dot version                                                                                                                                                                                                                                                                                                 
```

**Comment by Eluminae** [comment]
I recently dropped lightdm. Does the env variable is miss-setted ?

**Comment by Eluminae** [comment]
And I got a ~/bin/dot which is used  I dunno why x)

**Comment by Eluminae** [comment]
```
$ export GRAPHVIZ_DOT=/usr/bin/dot
```
Fixed the bug.
Should I just add it to my user wm init script ?

**Comment by arnaudroques** [comment]
> Should I just add it to my user init script ?

Yes, it sounds like the easiest solution.

That `~/bin/dot` that seems to call `git` is strange, but it's probably used by something else, so you should NOT remove it.

**Comment by Eluminae** [comment]
Okay cool ! The dot script is my own. It is just an "aliase" to access my dotfiles git.

ex : dot status, dot pull, dot add, ...
