### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by kozachynskyi** [plantuml/plantuml#240]
Hi, when I start in -gui mode I see no windows, just empty white screen. The command line version is working and producing png files. 

VoidLinux
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b00)
OpenJDK 64-Bit Server VM (build 25.202-b00, mixed mode)
xorg minimal

``
plantuml -v -gui 
(0.000 - 119 Mo) 114 Mo - PlantUML Version 1.2019.07
(0.002 - 119 Mo) 114 Mo - GraphicsEnvironment.isHeadless() false
(0.002 - 119 Mo) 114 Mo - Forcing resource load on OpenJdk
(0.415 - 119 Mo) 111 Mo - Showing MainWindow
(0.488 - 119 Mo) 111 Mo - Init done
(0.491 - 119 Mo) 111 Mo - Timer started
``

**Comment by kozachynskyi** [comment]
When running with -headless

plantuml -headless -v -gui
(0.000 - 119 Mo) 114 Mo - PlantUML Version 1.2019.07
(0.002 - 119 Mo) 114 Mo - GraphicsEnvironment.isHeadless() true
(0.003 - 119 Mo) 114 Mo - Forcing -Djava.awt.headless=true
(0.003 - 119 Mo) 114 Mo - java.awt.headless set as true
(0.003 - 119 Mo) 114 Mo - Forcing resource load on OpenJdk
Exception in thread "main" java.awt.HeadlessException
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at net.sourceforge.plantuml.swing.MainWindow2.<init>(MainWindow2.java:157)
        at net.sourceforge.plantuml.Run.main(Run.java:162)

**Comment by bakkeby** [comment]
Just for reference issues like this has to do with running a window manager that does not support reparenting. Try running this before starting the application. 
```bash
export _JAVA_AWT_WM_NONREPARENTING=1
```
