### ISSUE TITLE
IllegalArgumentException since version 1.2020.0

### ISSUE THREAD

**Issue by SaschaZ** [plantuml/plantuml#290]
Hi,

when building a classdiagram out of [this](https://gist.githubusercontent.com/SaschaZ/a3fa3204ed2921980b3cfed48a8d5d6a/raw/1ce8158a31526d20f0c47a644eb73b1dd52c3df0/sample.puml) code  PlantUml throws an IllegalArgumentException.

`Error java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
        at net.sourceforge.plantuml.cucadiagram.CucaDiagram.getGroup(CucaDiagram.java:434)
        at net.sourceforge.plantuml.classdiagram.command.CommandLinkClass.getFoo1(CommandLinkClass.java:285)
        at net.sourceforge.plantuml.classdiagram.command.CommandLinkClass.executeArg(CommandLinkClass.java:188)
        at net.sourceforge.plantuml.classdiagram.command.CommandLinkClass.executeArg(CommandLinkClass.java:69)
        at net.sourceforge.plantuml.command.SingleLineCommand2.execute(SingleLineCommand2.java:149)
        at net.sourceforge.plantuml.command.ProtectedCommand.execute(ProtectedCommand.java:55)
        at net.sourceforge.plantuml.AbstractPSystem.executeCommand(AbstractPSystem.java:124)
        at net.sourceforge.plantuml.command.UmlDiagramFactory.executeFewLines(UmlDiagramFactory.java:128)
        at net.sourceforge.plantuml.command.UmlDiagramFactory.createSystem(UmlDiagramFactory.java:110)
        at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:123)
        at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:153)
        at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
        at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:130)
        at de.gapps.plantuml.OutputFactory.create(OutputFactory.kt:27)
        at de.gapps.plantuml.OutputFactory.create(OutputFactory.kt:37)
        at de.gapps.plantuml.OutputFactory.createImage(OutputFactory.kt:51)
        at de.gapps.plantuml.PlantUmlAdapter.createImage(PlantUmlAdapter.kt)
        at de.gapps.plantuml.IOutputFactory$DefaultImpls.createImage$default(OutputFactory.kt:15)
        at de.gapps.plantuml.PlantUmlAdapter.toPlantUml(PlantUmlAdapter.kt:49)
        at de.gapps.plantuml.Main.main(PlantUmlAdapter.kt:82)
You should send a mail to plantuml@gmail.com or post to http://plantuml.com/qa with this log (V1.2020.00)
`

This exception is thrown with version `1.2020.0` and `1.2019.13`.
Version `1.2019.12` works fine.

**Comment by arnaudroques** [comment]
It seems to work one [the online server](http://www.plantuml.com/plantuml/uml/jLTVRnev47zcFyLAVKaZYaXEoaCQeG8XFQH2q96cqhsSlBi3kF7QAzkauNfyzvirowudB2jwxVaXmJFZd-VF-6Vl1sEPjkjK1C6A9n12cjbDc48QWJQ1UU8oOvgbOLzhzUrXnUCd2SQ4bvug5WmbtuCGHwHq0dgeXDBXcwuREpcBdvPQhMLIwExS2BOUJeOsR0c_0CciMAA-SRaChLv344YMWa5u21DuxlpDOGcwamacyy1nlw3LsWKnLodSCil2cvlmxBQD-_RlxaPlmruFhLgjLeAwwt1kDMBZVEkjv6acO9Z_pjSEs-WqhkrtgyN6cSoqoa3RpNKubZONMp0s5vO2PLUWvzIuzCm1uUy9s9LApinwiU0lxmkNtdg-jTQIsy8AvPznHgMNPyJSgjrl9oK1Scb1Bp1xHP3ZSjuKrcbEkhKf829wwTOUxle0nj8z7NZJZWXrgzQH08VMQhdMDWW1ocwoN5gsX8E_Zxv2RB7gTnhbhc1eioyjC069AwthYtaRUsumw7gbtLRc10-jxtFhRl-AMDFMUPcmMAkZVSEI8REmL9g3kGu_SMDlTWdiEMsMJT5dFwcHKF4JDAwADB2dcJBSSYNzjR7W8ErdHcHAMXIEanhXJB3D2XXHuI7ZCOopGnd5XHT4CEZ0eNzyGInn-e1r8oBvZDihlPbRPk4GGJ3xIScblqJmbDj-yg2HGdYk6YWbWCbSbqB2sOIdDKXELHTd9bZicjVvjc_332r13rd68YwuhKs_XkLQi3ptDSfdq7p1OwT-19aeVMYqBRld_FoZK14JvlpSzTl7zfuIgmxwRYoYnTimKieBe98x3lBF4z4kbAfOWMXcZEkRVZiSz3fV5PUULU5Z8_Ds4aXLSTIAQEuhxclYqe8s7vdm3lfHBZgPZPpBfpZTCUkeSAI6NDoW1EE2EU2NLWrfZAL1l6FKuGOfcq_kBWIANEtkW9kpMYQsI1L9JYCulJ1h4Bkk64HqSHrEM5OqTTlrKZb1srwlshNwVqh2vmWXW7Awxn38TLeOvG6CSEfvEnfFv-Napo-ZSJcv_GCdzPcWUvvKl4ohh4iJ_EgeqjAIF9ItoDPxtF0EIpjS9f01_f4MTss--iQLRMs35h5vxNEqSwIoAupZTz054z9R4KKIj0VaSZHjlnaESYWFY0cZfifErl7gGSq1QX2RdWQedQ_KMYG3yAAhCaczyaoQ3yQ24gVZatvah6QnOw6okMEhz8nX4YjHeiQsUjpGjNK7RKkviwQmdJn9b3X7-xlKN1m_tPJ-SUn-Tp2wL2dVnnRbV2VQ4IrINthcdgZlmpkXcArZqDElfYEN4zLKRX8VZrnGg3mfYLRbEQmd57zXNoRxSdtXTZLKQSOaLxA6pbbXrxGcFEkxF5nTaJmqz5HjLs7u-zssOMDB4RvobJdg7lLprdRbgXwwDElS7UHoIU4QjK4k7T-E_XhUJsRzwVX-IfsYDzaZq-H9LgE_l7OzTx1DViG6BDfGngpqIx2b0NamRF-NfcrkIYn5KFUmcBYFxelmtRj_Uc6TWVSXqW1m-RC0l_qiWFk2_c4Cyhvw_GviWAFVfBMG_mdeW2zUNnP4K67NyKpds84BViYwSyAvVHV-6iZW0wx6l0J_0W00).

I think it has been solved in last beta http://beta.plantuml.net/plantuml.jar

**Comment by SaschaZ** [comment]
I can confirm that. 

Do you also have a maven repository for the beta version?

**Comment by arnaudroques** [comment]
We've just pushed 1.2020.1 to maven that should fix this issue.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @SaschaZ for the report.
- Thanks PlantUML team for your work.

Regards.
