### ISSUE TITLE
plantuml don't work

### ISSUE THREAD

**Issue by iT-Boyer** [plantuml/plantuml#314]
```
$ plantuml -version
PlantUML version 1.2020.06 (Sun Apr 05 20:38:32 CST 2020)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Java Version: 1.8.0_241-b07
Operating System: Mac OS X
Default Encoding: UTF-8
Language: zh
Country: CN
Machine: ProOne.local
PLANTUML_LIMIT_SIZE: 4096
Processors: 24
Max Memory: 7,635,730,432
Total Memory: 514,850,816
Free Memory: 493,291,560
Used Memory: 21,559,256
Thread Active Count: 1
```

```log
Exception java.lang.IllegalStateException
net.sourceforge.plantuml.cucadiagram.UnparsableGraphvizException: java.lang.IllegalStateException
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:434)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:107)
	at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:71)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:651)
	at net.sourceforge.plantuml.classdiagram.ClassDiagram.exportDiagramInternal(ClassDiagram.java:196)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:201)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:158)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:113)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:358)
	at net.sourceforge.plantuml.Run.main(Run.java:165)
Caused by: java.lang.IllegalStateException
	at net.sourceforge.plantuml.svek.DotStringFactory.solve(DotStringFactory.java:356)
	at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:421)````

**Comment by abhijeet-pathak** [comment]
This usually happens while exporting the image.
Could you please provide more information or give some sample?
