### ISSUE TITLE
Preprocessor line merging breaks ditaa diagrams with sloped edge at line end

### ISSUE THREAD

**Issue by t-8ch** [plantuml/plantuml#324]
In V1.2020.0 a feature was implemented to span preprocessor arguments over
multiple lines
(https://forum.plantuml.net/10597/preprocessorv2-multiline-function-invocation)

This however breaks ditaa diagrams with sloped edges at the end of a line.

```plantuml
@startditaa
+--------\
|  Text  |
+--------+
@endditaa
```

Going back to a version before V1.2020.0 or removing
`net.sourceforge.plantuml.preproc2.ReadFilterMergeLines` from the processing
pipeline makes the diagram render correctly.

Also the error reporting of PSystemDitaa is only printing to System.err.
Could this be changed to use the normal error reporting?

If you want I can try to prepare a PR to limit the linefolding to preprocessor
arguments.

## Preprocessor output
```
+--------|  Text  |
+--------+
```

## Error message
(Error message varies between affected diagrams, depending on what exactly is on the next line)
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.sourceforge.plantuml.ditaa.PSystemDitaa.exportDiagramNow(PSystemDitaa.java:126)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:156)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:99)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:159)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:520)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:404)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:372)
	at net.sourceforge.plantuml.Run.main(Run.java:188)
Caused by: java.lang.RuntimeException: cannot create closed shape from boundary cells, nowhere to go from (11, 2) coming from (11, 3) in grid:
    012345678901234567890123456789
 0 (                       )
 1 (                       )
 2 (  +--------|  Text  |  )
 3 (  +--------+           )
 4 (                       )
 5 (                       )

maybe you have an edge pointing nowhere?
	at org.stathissideris.ascii2image.graphics.DiagramComponent.createClosedFromBoundaryCells(DiagramComponent.java:110)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:323)
	... 13 more
```

**Comment by arnaudroques** [comment]
Thanks for the report.
We're going to look at this.

**Comment by arnaudroques** [comment]
This is fixed in last beta http://beta.plantuml.net/plantuml.jar
It will be released soon.

**Comment by t-8ch** [comment]
Thanks a lot! Any way I can look at the commit before the release?

**Comment by t-8ch** [comment]
I can also confirm the the beta works with our non-example diagram that exhibited the error.

**Comment by t-8ch** [comment]
Please don't close yet. This seems to have triggered another issue.
(I will provide details soon)

**Comment by t-8ch** [comment]
Problem seems to be somewhere else.
Thanks for the fast fix!
