### ISSUE TITLE
ASCII Art java.lang.IllegalArgumentException in State Diagram

### ISSUE THREAD

**Issue by MartensCedric** [plantuml/plantuml#391]
```
@startuml
[*] --> Uncatalogued
Uncatalogued --> Catalogued : Added to selection
Uncatalogued --> Discarded : Unwanted or damaged
Catalogued --> Lent : Student borrows book
state Lent {
 [*] --> Overdue : Student does not return book by due date
Overdue --> Lost : [Loan Maturity > 12 months] Book not returned
}
Catalogued --> Discarded : Unwanted or damaged
Lent --> Catalogued : Student returns the book
@enduml
```
```
java.lang.IllegalArgumentException
	at net.sourceforge.plantuml.posimo.Path.<init>(Path.java:53)
	at net.sourceforge.plantuml.cucadiagram.dot.CucaDiagramTxtMaker.<init>(CucaDiagramTxtMaker.java:113)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.createFilesTxt(CucaDiagram.java:678)
	at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:628)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:173)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagramInternal(DiagramResponse.java:162)
	at net.sourceforge.plantuml.servlet.DiagramResponse.sendDiagram(DiagramResponse.java:123)
	at net.sourceforge.plantuml.servlet.UmlDiagramService.doGet(UmlDiagramService.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:717)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1644)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:164)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1615)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1110)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:479)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1044)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:459)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:281)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by The-Lum** [comment]
Hi @MartensCedric,

FYI, here is the result with the last version:
>[![](https://www.planttext.com/api/plantuml/svg/XL4xYm913ExdLwG-iBWhhn0VLtfOY9LOn4tGvNOJcCae8lvtixCiUbfO9I7VApEJP1WjjqtOV6nXD1h3MYeqR7IVcSBZKBRp-_WDKoAlff2uuSfgbLV2JvqgZ5JmQpcXcBSQWR35lJlC_yCNBER8bMNgkft6gAVaLV-2HpNk4PS0GzxbaIDbVY2HSW9HWyYMenGoxCxGeSWbma0fXfewmyr2KU0NdL3R6SRm-GMjYXtI5cOT_wxdeQ_FiTzTMKA_lDyGkDTDO0VkBvsmaF_93G00)](https://www.planttext.com/?text=XL4xYm913ExdLwG-iBWhhn0VLtfOY9LOn4tGvNOJcCae8lvtixCiUbfO9I7VApEJP1WjjqtOV6nXD1h3MYeqR7IVcSBZKBRp-_WDKoAlff2uuSfgbLV2JvqgZ5JmQpcXcBSQWR35lJlC_yCNBER8bMNgkft6gAVaLV-2HpNk4PS0GzxbaIDbVY2HSW9HWyYMenGoxCxGeSWbma0fXfewmyr2KU0NdL3R6SRm-GMjYXtI5cOT_wxdeQ_FiTzTMKA_lDyGkDTDO0VkBvsmaF_93G00)

And it seems that the issue does not occur. 
_Perhaps we can close this issue._

Regards,
Th.

**Comment by The-Lum** [comment]
Oups/Oops, I didn't read the whole title...

In fact, the issue remains on `-utext` export:
```.cy
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:222)
	at net.sourceforge.plantuml.posimo.Path.<init>(Path.java:61)
	at net.sourceforge.plantuml.dot.CucaDiagramTxtMaker.<init>(CucaDiagramTxtMaker.java:118)
	at net.atmp.CucaDiagram.createFilesTxt(CucaDiagram.java:373)
	at net.atmp.CucaDiagram.exportDiagramInternal(CucaDiagram.java:397)

```
FYI only some part or type of diagrams are available with ASCII-Art _(and currently mainly only `sequence` diagram)_...
See:
- https://plantuml.com/ascii-art

_Awaiting enhancement on ASCII-Art..._
Regards,
Th.
