### ISSUE TITLE
conditionStyle foo1 not work

### ISSUE THREAD

**Issue by impatrickwang** [plantuml/plantuml#400]
Hi team,
ConditionStyle foo1 does not work for me. I use `plantuml.1.2020.17.jar`.

Following is my case:
```
@startuml
skinparam ConditionStyle foo1
start
-> test;
if (test?) then (yes)
    :ok;
else (no)
    :bad;
endif
stop
@enduml
```

then I got such output:
```java
(0.000 - 128 Mo) 121 Mo - SecurityProfile LEGACY
(0.017 - 128 Mo) 121 Mo - PlantUML Version 1.2020.17
(0.018 - 128 Mo) 121 Mo - GraphicsEnvironment.isHeadless() false
(0.018 - 128 Mo) 121 Mo - Forcing resource load on OpenJdk
(0.696 - 128 Mo) 119 Mo - Found 1 files
(0.696 - 128 Mo) 119 Mo - Working on test.uml
(0.718 - 128 Mo) 118 Mo - Setting current dir: /Users/wanglihao/Documents/wiki/AI2B/digital-human/cloud/dialog-intelligent-interrupt/.
(0.718 - 128 Mo) 118 Mo - Setting current dir: /Users/wanglihao/Documents/wiki/AI2B/digital-human/cloud/dialog-intelligent-interrupt
(0.719 - 128 Mo) 118 Mo - Using default charset
(0.727 - 128 Mo) 118 Mo - Reading from test.uml
(0.769 - 128 Mo) 116 Mo - Reading file: test.uml
(1.001 - 128 Mo) 114 Mo - Compilation duration 230
(1.001 - 128 Mo) 114 Mo - Regex total/invoked/compiled 178/162/79
(1.001 - 128 Mo) 114 Mo - Matches created 21
(1.003 - 128 Mo) 114 Mo - Creating file: /Users/wanglihao/Documents/wiki/AI2B/digital-human/cloud/dialog-intelligent-interrupt/test.png
java.lang.IllegalStateException
        at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.cond.ConditionalBuilder.getDiamond1(ConditionalBuilder.java:264)
        at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.cond.ConditionalBuilder.getDiamond1(ConditionalBuilder.java:235)
        at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.cond.ConditionalBuilder.createWithLinks(ConditionalBuilder.java:214)
        at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.cond.ConditionalBuilder.create(ConditionalBuilder.java:159)
        at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.FtileFactoryDelegatorIf.createIf(FtileFactoryDelegatorIf.java:112)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createIf(FtileFactoryDelegator.java:196)
        at net.sourceforge.plantuml.activitydiagram3.InstructionIf.createFtile(InstructionIf.java:114)
        at net.sourceforge.plantuml.activitydiagram3.InstructionList.createFtile(InstructionList.java:102)
        at net.sourceforge.plantuml.activitydiagram3.ftile.Swimlanes.drawU(Swimlanes.java:215)
        at net.sourceforge.plantuml.ugraphic.comp.CompressionXorYBuilder.getPiecewiseAffineTransform(CompressionXorYBuilder.java:51)
        at net.sourceforge.plantuml.ugraphic.comp.CompressionXorYBuilder.build(CompressionXorYBuilder.java:44)
        at net.sourceforge.plantuml.activitydiagram3.ActivityDiagram3.exportDiagramInternal(ActivityDiagram3.java:212)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:189)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsActivityDiagram3(PSystemUtils.java:176)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:95)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:526)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:410)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:377)
        at net.sourceforge.plantuml.Run.main(Run.java:192)
(1.486 - 128 Mo) 53 Mo - Creating image 831x931
(1.695 - 128 Mo) 70 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.808 - 128 Mo) 64 Mo - Number of image(s): 1
```

Please help me, thanks in advance.

**Comment by arnaudroques** [comment]
Thanks for the report.
This has been fixed in last beta http://beta.plantuml.net/plantuml.jar
Tell us if you find other issues!

BTW, does anyone have a better idea than `foo1` to describe this ConditionStyle ? 
We are really out of inspiration here :-)
But we would like to put something more meaningful...

**Comment by impatrickwang** [comment]
Thanks, it works.
Why not just call it "diamondInside"?

**Comment by arnaudroques** [comment]
Ok, last beta http://beta.plantuml.net/plantuml.jar supports now InsideDiamond
"foo1" is still working for ascending compatibility

**Comment by btz606** [comment]
test
