### ISSUE TITLE
Does salt support pdf exporting?

### ISSUE THREAD

**Issue by andrew-hm** [plantuml/plantuml#455]
I ask because, I can export a salt diagram to other formats, eps, png, but not pdf. I downloaded the extra pdfs and can export uml diagrams to pdf with no issue. Here's the salt wireframe (from the examples on your website)

```
@startsalt
skinparam shadowing false
header some header
footer some footer
title My title
caption This is caption

legend
The legend
end legend

{+
Login | "MyName "
Password | "**** "
[Cancel] | [ OK ]
}
@endsalt       
```
These commands all work

- `java -Djava.awt.headless=true -jar /path/to/plantuml.jar -failfast2 -nbtread auto -charset UTF-8 -teps  salt.puml`
- `java -Djava.awt.headless=true -jar /path/to/plantuml.jar -failfast2 -nbtread auto -charset UTF-8 -tsvg  salt.puml`
- `java -Djava.awt.headless=true -jar /path/to/plantuml.jar -failfast2 -nbtread auto -charset UTF-8 -tpng  salt.puml`

This one fails

- `java -Djava.awt.headless=true -jar /path/to/plantuml.jar -failfast2 -nbtread auto -charset UTF-8 -tpdf salt.puml`

So wasn't sure if salt wireframes exporting to pdf was supported or not. Here's my version

```
PlantUML version 1.2021.00 (Sun Jan 10 02:25:05 PST 2021)
(GPL source distribution)
Java Runtime: OpenJDK Runtime Environment
JVM: OpenJDK 64-Bit Server VM
Default Encoding: UTF-8
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.46.0 (20210118.1747)
Installation seems OK. File generation OK
```

This is the error from Java

```
java.lang.UnsupportedOperationException: PDF
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:307)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:145)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:129)
	at net.sourceforge.plantuml.salt.PSystemSalt.exportDiagramNow(PSystemSalt.java:155)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:154)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:97)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:538)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:422)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:389)
	at net.sourceforge.plantuml.Run.main(Run.java:191)
Exception in thread "main" java.lang.UnsupportedOperationException: PDF
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:307)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:145)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:129)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:245)
	at net.sourceforge.plantuml.salt.PSystemSalt.exportDiagramNow(PSystemSalt.java:158)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:154)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:97)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:538)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:422)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:389)
	at net.sourceforge.plantuml.Run.main(Run.java:191)
```

**Comment by albert-github** [comment]
Seen the comment https://github.com/plantuml/plantuml/issues/341#issuecomment-971834021 I tried this example and it still gave a stacktrace:
```
java.lang.UnsupportedOperationException: PDF
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:429)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:273)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.write(ImageBuilder.java:247)
        at net.sourceforge.plantuml.salt.PSystemSalt.exportDiagramNow(PSystemSalt.java:122)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:178)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:519)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:402)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:369)
        at net.sourceforge.plantuml.Run.main(Run.java:204)
Exception in thread "main" java.lang.UnsupportedOperationException: PDF
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.createUGraphic(ImageBuilder.java:429)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:273)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.write(ImageBuilder.java:247)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:204)
        at net.sourceforge.plantuml.salt.PSystemSalt.exportDiagramNow(PSystemSalt.java:125)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:178)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:519)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:402)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:369)
        at net.sourceforge.plantuml.Run.main(Run.java:204)
```

whilst the skin parameter example from https://github.com/plantuml/plantuml/issues/341#issue-641859670 rendered OK.

The plantuml version:
```
PlantUML version 1.2021.15beta7 (Unknown compile time)
(GPL source distribution)
Java Runtime: Java(TM) SE Runtime Environment
JVM: Java HotSpot(TM) 64-Bit Server VM
Default Encoding: Cp1252
Language: en
Country: US

PLANTUML_LIMIT_SIZE: 4096

Dot version: dot - graphviz version 2.44.1 (20200629.0846)
Installation seems OK. File generation OK
```

(I also installed required jar files as indicated at https://plantuml.com/pdf)
