### ISSUE TITLE
UnsupportedOperationException in while loops

### ISSUE THREAD

**Issue by werererer** [plantuml/plantuml#491]
This happens in the beta syntax of the activity diagrams. Here a simple example where it happens:
```
@startuml
skinparam ConditionStyle InsideDiamond
while (test)
    break
endwhile
@enduml
```
This exception is yielded by the break in the loop (if I omit it it will compile successfully) and only occures when I use skinparam ConditionStyle Inside Diamond
```
supportedOperationException: class net.sourceforge.plantuml.activitydiagram3.ftile.vertical.FtileDiamondSquare
	at net.sourceforge.plantuml.activitydiagram3.ftile.AbstractFtile.getMyChildren(AbstractFtile.java:102)
	at net.sourceforge.plantuml.activitydiagram3.ftile.Genealogy.process(Genealogy.java:57)
	at net.sourceforge.plantuml.activitydiagram3.ftile.Genealogy.process(Genealogy.java:62)
	at net.sourceforge.plantuml.activitydiagram3.ftile.Genealogy.process(Genealogy.java:62)
	at net.sourceforge.plantuml.activitydiagram3.ftile.Genealogy.<init>(Genealogy.java:52)
	at net.sourceforge.plantuml.activitydiagram3.ftile.vcompact.FtileFactoryDelegatorWhile.createWhile(FtileFactoryDelegatorWhile.java:115)
	at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createWhile(FtileFactoryDelegator.java:192)
	at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createWhile(FtileFactoryDelegator.java:192)
	at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createWhile(FtileFactoryDelegator.java:192)
	at net.sourceforge.plantuml.activitydiagram3.ftile.FtileFactoryDelegator.createWhile(FtileFactoryDelegator.java:192)
	at net.sourceforge.plantuml.activitydiagram3.InstructionWhile.createFtile(InstructionWhile.java:112)
	at net.sourceforge.plantuml.activitydiagram3.InstructionList.createFtile(InstructionList.java:102)
	at net.sourceforge.plantuml.activitydiagram3.ftile.Swimlanes.drawU(Swimlanes.java:215)
	at net.sourceforge.plantuml.ugraphic.comp.CompressionXorYBuilder.getPiecewiseAffineTransform(CompressionXorYBuilder.java:51)
	at net.sourceforge.plantuml.ugraphic.comp.CompressionXorYBuilder.build(CompressionXorYBuilder.java:44)
	at net.sourceforge.plantuml.activitydiagram3.ActivityDiagram3.exportDiagramInternal(ActivityDiagram3.java:211)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:176)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:140)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagramsActivityDiagram3(PSystemUtils.java:176)
	at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:95)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:160)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:538)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:422)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:389)
	at net.sourceforge.plantuml.Run.main(Run.java:198)
```
I compile on linux with: 
```
plantuml -tepd file.puml 
```
and I have the the version: 1.2021.0-1

**Comment by arnaudroques** [comment]
Thanks for the report: this is fixed in last release 1.2021.3
