### ISSUE TITLE
`-graphvizdot` no longer works

### ISSUE THREAD

**Issue by myint** [plantuml/plantuml#53]
`-graphvizdot` no longer works in version `1.2017.12`.

```
$ java -jar plantuml.jar -graphvizdot /opt/local/bin/dot example.puml
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

The environment variable `GRAPHVIZ_DOT` seems to work though.

```
$ GRAPHVIZ_DOT=/opt/local/bin/dot java -jar plantuml.jar example.puml
````

**Comment by arnaudroques** [comment]
Thanks for the report. Unfortunately, we cannot reproduce this bug.
Could you try (with verbose flag) on latest beta (we've added some trace) ?
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

`java -jar plantuml.jar -verbose -graphvizdot /opt/local/bin/dot example.puml`

And post here the log ?
Thanks!

**Comment by myint** [comment]
This may be a heisenbug.

```
$ cat example.puml
@startuml

title test

[*] --> root

@enduml
```

```
$ java -jar plantuml.jar -graphvizdot /opt/local/bin/dot example.puml
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
```

With verbose, the problem disappears:

```
$ java -jar plantuml.jar -verbose -graphvizdot /opt/local/bin/dot example.puml
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2017.13beta3
(0.002 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false
(0.801 - 245 Mo) 236 Mo - Setting current dir: .
(0.801 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.802 - 245 Mo) 236 Mo - Using default charset
(0.806 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.811 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.811 - 245 Mo) 236 Mo - Reading file: example.puml
(1.048 - 245 Mo) 192 Mo - Creating file: /Users/myint/Downloads/example.png
(1.101 - 245 Mo) 185 Mo - Starting Graphviz process [/opt/local/bin/dot, -Tsvg]
(1.101 - 245 Mo) 185 Mo - DotString size: 312
(1.113 - 245 Mo) 182 Mo - Ending process ok
(1.113 - 245 Mo) 182 Mo - Ending Graphviz process
(1.147 - 245 Mo) 181 Mo - Creating image 67x169
(1.219 - 245 Mo) 235 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.259 - 245 Mo) 235 Mo - Number of image(s): 1
```

```
$ file example.png
example.png: PNG image data, 67 x 169, 8-bit/color RGB, non-interlaced
```

**Comment by myint** [comment]
Oh, actually the problem reappears if I change the argument order:

```
$ java -jar plantuml.jar  -graphvizdot /opt/local/bin/dot example.puml -verbose
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2017.13beta3
(0.002 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false
(0.808 - 245 Mo) 236 Mo - Setting current dir: .
(0.808 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.809 - 245 Mo) 236 Mo - Using default charset
(0.813 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.818 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.819 - 245 Mo) 236 Mo - Reading file: example.puml
(1.049 - 245 Mo) 192 Mo - Creating file: /Users/myint/Downloads/example.png
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
java.io.IOException: Cannot run program "/usr/bin/dot": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.startThreads(ProcessRunner.java:163)
	at net.sourceforge.plantuml.cucadiagram.dot.ProcessRunner$MainThread.runJob(ProcessRunner.java:123)
	at net.sourceforge.plantuml.api.TimeoutExecutor$MyThread.run(TimeoutExecutor.java:79)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
(1.176 - 245 Mo) 226 Mo - Creating image 284x233
(1.205 - 245 Mo) 212 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.258 - 245 Mo) 211 Mo - Number of image(s): 1
```

**Comment by arnaudroques** [comment]
This is really weird.
Could you try with beta 6 ?
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
We are interested with logs when it does NOT work.
Thanks!

**Comment by arnaudroques** [comment]
I think we've solved it.
You can try beta 7 here https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
It was related to class loading order, which was depending on option order in command line!
Tell us if it's working for you now!
Thanks!

**Comment by myint** [comment]
Thanks, that fixed it!

```
$ java -jar plantuml.jar -verbose -graphvizdot /opt/local/bin/dot example.puml
Setting GraphViz to /opt/local/bin/dot
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2017.13beta7
(0.001 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false
(0.842 - 245 Mo) 236 Mo - Setting current dir: .
(0.842 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.843 - 245 Mo) 236 Mo - Using default charset
(0.847 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.852 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.852 - 245 Mo) 236 Mo - Reading file: example.puml
(1.081 - 245 Mo) 192 Mo - Creating file: /Users/myint/Downloads/example.png
(1.094 - 245 Mo) 191 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.094 - 245 Mo) 191 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.132 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.132 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.136 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.136 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.137 - 245 Mo) 186 Mo - Starting Graphviz process [/opt/local/bin/dot, -Tsvg]
(1.137 - 245 Mo) 186 Mo - DotString size: 312
(1.150 - 245 Mo) 184 Mo - Ending process ok
(1.150 - 245 Mo) 184 Mo - Ending Graphviz process
(1.182 - 245 Mo) 182 Mo - Creating image 67x169
(1.250 - 245 Mo) 181 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.290 - 245 Mo) 181 Mo - Number of image(s): 1
```

```
$ java -jar plantuml.jar -graphvizdot /opt/local/bin/dot example.puml -verbose
Setting GraphViz to /opt/local/bin/dot
(0.000 - 245 Mo) 237 Mo - PlantUML Version 1.2017.13beta7
(0.002 - 245 Mo) 237 Mo - GraphicsEnvironment.isHeadless() false
(0.792 - 245 Mo) 236 Mo - Setting current dir: .
(0.792 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.793 - 245 Mo) 236 Mo - Using default charset
(0.797 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.802 - 245 Mo) 236 Mo - Setting current dir: /Users/myint/Downloads
(0.802 - 245 Mo) 236 Mo - Reading file: example.puml
(1.033 - 245 Mo) 192 Mo - Creating file: /Users/myint/Downloads/example.png
(1.046 - 245 Mo) 191 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.047 - 245 Mo) 191 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.088 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.089 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.091 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.091 - 245 Mo) 186 Mo - GraphvizUtils::dotExecutable=/opt/local/bin/dot
(1.091 - 245 Mo) 186 Mo - Starting Graphviz process [/opt/local/bin/dot, -Tsvg]
(1.091 - 245 Mo) 186 Mo - DotString size: 312
(1.103 - 245 Mo) 184 Mo - Ending process ok
(1.103 - 245 Mo) 184 Mo - Ending Graphviz process
(1.138 - 245 Mo) 182 Mo - Creating image 67x169
(1.196 - 245 Mo) 181 Mo - Ok for com.sun.imageio.plugins.png.PNGMetadata
(1.239 - 245 Mo) 181 Mo - Number of image(s): 1
```

**Comment by arnaudroques** [comment]
Thanks for the remote debug!
We've remove the log in the last beta
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0
This will be published in next official release.
Regards,

**Comment by pjscopeland** [comment]
I have just encountered this same issue three years later on a new Mac, but my problem was fixed my running `brew install graphviz`.

**Comment by mirajgodha** [comment]
On Mac 10.15.7, brew install graphviz solved this issue for me. Thanks @pjscopeland

**Comment by Kerrhylon** [comment]
Dito macOS 15.0.1, thanks
