### ISSUE TITLE
Not work on testdot

### ISSUE THREAD

**Issue by DitaAjiPratama** [plantuml/plantuml#558]
I'm still not sure whether this is an issue from the java side or from the plantuml side.

My java version:
```
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)
```

My graphviz:
`dot - graphviz version 2.43.0 (0)`

I want to run this:
`java -jar plantuml.jar -testdot`

And here is the error result:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2387)
        at java.base/java.lang.Runtime.load0(Runtime.java:746)
        at java.base/java.lang.System.load(System.java:1857)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:310)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:280)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2392)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
        at java.base/java.lang.System.loadLibrary(System.java:1893)
        at java.desktop/java.awt.image.ColorModel$1.run(ColorModel.java:209)
        at java.desktop/java.awt.image.ColorModel$1.run(ColorModel.java:207)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at java.desktop/java.awt.image.ColorModel.loadLibraries(ColorModel.java:206)
        at java.desktop/java.awt.image.ColorModel.<clinit>(ColorModel.java:219)
        at java.desktop/java.awt.image.BufferedImage.<clinit>(BufferedImage.java:286)
        at net.sourceforge.plantuml.FileFormat.<clinit>(FileFormat.java:124)
        at net.sourceforge.plantuml.Option.<init>(Option.java:99)
        at net.sourceforge.plantuml.Run.main(Run.java:93)
```

**Comment by DitaAjiPratama** [comment]
I found the solution, I must install both java and javac, and use it in same version of java.
