### ISSUE TITLE
License output broken

### ISSUE THREAD

**Issue by c-lipka** [plantuml/plantuml#575]
Running
~~~
java -jar plantuml.jar -license
~~~
with a freshly downloaded .jar file (identifying as PlantUML version 1.2021.7 / GPL source distribution) on a Windows 10 command line (powershell or cmd) results in:
~~~
Exception in thread "main" java.lang.NullPointerException
        at net.sourceforge.plantuml.security.SFile.isDirectory(SFile.java:131)
        at net.sourceforge.plantuml.version.LicenseInfo.fileCandidates(LicenseInfo.java:201)
        at net.sourceforge.plantuml.version.LicenseInfo.retrieveNamedSlow(LicenseInfo.java:110)
        at net.sourceforge.plantuml.version.LicenseInfo.retrieveQuick(LicenseInfo.java:89)
        at net.sourceforge.plantuml.version.License.getTextFull(License.java:480)
        at net.sourceforge.plantuml.OptionPrint.printLicense(OptionPrint.java:173)
        at net.sourceforge.plantuml.Option.<init>(Option.java:295)
        at net.sourceforge.plantuml.Run.main(Run.java:87)
~~~

**Comment by c-lipka** [comment]
Addendum: The alternative mechanism, using the following special diagram:
~~~
@startuml
license
@enduml
~~~
is also broken, producing a somewhat longer but similar stack trace.

**Comment by c-lipka** [comment]
Update:

The exception only seems to be thrown when the `.jar` file is located in a directory that contains certain problematic characters (in this case spaces).

**Comment by arnaudroques** [comment]
Thanks for the report.
This seems to be connected to some value in `java.class.path` environment variable.

Could you try last beta http://beta.plantuml.net/plantuml.jar ?
We _may_ have fixed this.

Thanks!

**Comment by c-lipka** [comment]
Seems to work nicely now. (I've only checked `java -jar plantuml.jar -license`, not the special diagram, but I presume that since the root cause is the same, that's also solved.)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @c-lipka for the report.
- Thanks PlantUML team for your work.

Regards.
