### ISSUE TITLE
getting a java exception trying to render a simple diagram.

### ISSUE THREAD

**Issue by olymk2** [plantuml/plantuml#69]
Trying to render my first diagram and i have hit this error and unsure how to resolve ?

openjdk 9-Ubuntu
OpenJDK Runtime Environment (build 9-Ubuntu+0-9b161-1)
OpenJDK 64-Bit Server VM (build 9-Ubuntu+0-9b161-1, mixed mode)

```
Exception in thread "main" java.lang.IllegalAccessError: class net.sourceforge.plantuml.png.PngIOMetadata (in unnamed module @0x23941fb4) cannot access class com.sun.imageio.plugins.png.PNGMetadata (in module java.desktop) because module java.desktop does not export com.sun.imageio.plugins.png to unnamed module @0x23941fb4
	at net.sourceforge.plantuml.png.PngIOMetadata.writeWithMetadata(PngIOMetadata.java:60)
	at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:86)
	at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:80)
	at net.sourceforge.plantuml.ugraphic.g2d.UGraphicG2d.writeImageTOBEMOVED(UGraphicG2d.java:219)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:250)
	at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageTOBEMOVED(ImageBuilder.java:172)
	at net.sourceforge.plantuml.sequencediagram.graphic.SequenceDiagramFileMakerPuma2.createOne(SequenceDiagramFileMakerPuma2.java:234)
	at net.sourceforge.plantuml.sequencediagram.SequenceDiagram.exportDiagramInternal(SequenceDiagram.java:225)
	at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:236)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:134)
	at net.sourceforge.plantuml.SourceStringReader.outputImage(SourceStringReader.java:154)
	at net.sourceforge.plantuml.Pipe.managePipe(Pipe.java:95)
	at net.sourceforge.plantuml.Run.managePipe(Run.java:285)
	at net.sourceforge.plantuml.Run.main(Run.java:136)

```

**Comment by arnaudroques** [comment]
Indeeed, the com.sun.imageio.plugins.png.PNGMetadata class does not exist on OpenJDK.

However, we have made a check on non-Oracle JDK, that should work even on OpenJDK.
(In that case, we simply don't put metadata in Png export)
This check is obviously buggy.

Could you try if you have a better result with last beta ?
https://www.dropbox.com/s/koo42q3d9gxw288/plantuml.jar?dl=0

Thanks!

**Comment by olymk2** [comment]
That's great just tested and I now have an image rendering in emacs, thanks for that :)

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @olymk2 for the report.
- Thanks PlantUML team for your work.
	
Regards.

**Comment by testoptimal** [comment]
I am also having the same issue and the jar file fixed it for me.  However I am using following maven dependency, do you have a new version of the maven build?

		
		<dependency>
		    <groupId>net.sourceforge.plantuml</groupId>
		    <artifactId>plantuml</artifactId>
		    <version>8059</version>
		</dependency>

**Comment by The-Lum** [comment]
Hi @testoptimal-support, and all,

FYI: here is the last maven build on `1.2023.12`:
```xml
	<!-- https://mvnrepository.com/artifact/net.sourceforge.plantuml/plantuml -->
	<dependency>
	    <groupId>net.sourceforge.plantuml</groupId>
	    <artifactId>plantuml</artifactId>
	    <version>1.2023.12</version>
	</dependency>
```

Regards,
Th.
