### ISSUE TITLE
YAML Diagram - Cannot render a list contain a key value pair

### ISSUE THREAD

**Issue by ttelang** [plantuml/plantuml#708]
Can not render the following code

```yaml
@startyaml
- DATA
- 
  data: value
@endyaml
```
**Expected Result:** 
Two nodes and a arrow representing the YAML data should be rendered.  

**Actual Result**
Gives error message

"You data do not sounds like YAML data"

with exception as below: 

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at net.sourceforge.plantuml.yaml.SimpleYamlParser.getForceArray(SimpleYamlParser.java:136)
	at net.sourceforge.plantuml.yaml.SimpleYamlParser.parseSingleLine(SimpleYamlParser.java:87)
	at net.sourceforge.plantuml.yaml.SimpleYamlParser.parse(SimpleYamlParser.java:59)
	at net.sourceforge.plantuml.yaml.YamlDiagramFactory.createSystem(YamlDiagramFactory.java:79)
	at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:133)
	at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:163)
	at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:151)
	at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:527)
	at net.sourceforge.plantuml.Run.processArgs(Run.java:410)
	at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:377)
	at net.sourceforge.plantuml.Run.main(Run.java:205)
```

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_ 👀 
This is now fixed with last release [V1.2025.1](https://github.com/plantuml/plantuml/releases/tag/v1.2025.1)

>[![](https://img.plantuml.biz/plantuml/dsvg/SoWkIImggKpCpU7bAiaioKbLCDGpCZ0orJDKq5TGBKijAixCpzFGvENYvT9LS74CSGJHl5mA2Yc99ObM2cM9EQMfl5mEgNaf83C0)](https://editor.plantuml.com/uml/SoWkIImggKpCpU7bAiaioKbLCDGpCZ0orJDKq5TGBKijAixCpzFGvENYvT9LS74CSGJHl5mA2Yc99ObM2cM9EQMfl5mEgNaf83C0)

- Thanks @ttelang for the report.
- Thanks PlantUML team and @arnaudroques for your work.

Regards.
