### ISSUE TITLE
Provide an option to disable the flash code generation

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#822]
Depending on the input the generation can be memory-intensive. 
I can see that the code is using a condition:

https://github.com/plantuml/plantuml/blob/1d6d3e847752b30753c43190374c93caef4063d0/src/net/sourceforge/plantuml/flashcode/FlashCodeUtilsZxing.java#L53-L58

But, as far as I know, `USE_FLASH` is a constant and it's not possible to override the value.

Would you accept a pull request that read the value of the environment variable `PLANTUML_USE_FLASH` (or `PLANTUML_GENERATE_FLASH_CODE`) to enable or disable this feature? For backward compatibility, if the environment variable is absent, the default value will be "true".

For reference, I get the following error in a Vert.x application:

```
io.vertx.core.VertxException: Thread blocked
	at app//ext.plantuml.com.google.zxing.common.BitArray.makeArray(BitArray.java:233)
	at app//ext.plantuml.com.google.zxing.common.BitArray.ensureCapacity(BitArray.java:53)
	at app//ext.plantuml.com.google.zxing.common.BitArray.appendBits(BitArray.java:164)
	at app//ext.plantuml.com.google.zxing.qrcode.encoder.Encoder.append8BitBytes(Encoder.java:521)
	at app//ext.plantuml.com.google.zxing.qrcode.encoder.Encoder.appendBytes(Encoder.java:456)
	at app//ext.plantuml.com.google.zxing.qrcode.encoder.Encoder.encode(Encoder.java:95)
	at app//ext.plantuml.com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:64)
	at app//net.sourceforge.plantuml.flashcode.FlashCodeUtilsZxing.exportFlashcode(FlashCodeUtilsZxing.java:65)
	at app//net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:180)
	at app//net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:162)
	at app//net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:155)
	at app//net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:157)
	at app//io.kroki.server.service.Plantuml.convert(Plantuml.java:280)
	at app//io.kroki.server.service.Plantuml.lambda$convert$5(Plantuml.java:236)
	at app//io.kroki.server.service.Plantuml$$Lambda$194/0x00000001002d4840.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$198/0x00000001002d3c40.handle(Unknown Source)
	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$196/0x00000001002d4440.run(Unknown Source)
	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at app//io.vertx.core.impl.TaskQueue$$Lambda$103/0x00000001001adc40.run(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.9.1/java.lang.Thread.run(Unknown Source)
```

This exception is thrown when a thread is blocked for more than 60 seconds.

**Comment by arnaudroques** [comment]
> Depending on the input the generation can be memory-intensive.

Before providing a way to completely disable QrCode generation, we'd like to better understand what's going on.

On last commit https://github.com/plantuml/plantuml/commit/51ee3fb7c7d5612e28a75e536350e74721dc0cf3 we add a protection against memory over use. Is it possible for you to test [last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot) and tell us if it's work better this way ?

Thanks

**Comment by Mogztter** [comment]
> Before providing a way to completely disable QrCode generation, we'd like to better understand what's going on.

Unfortunately, I wasn't able to retrieve the text input that produces this error 😞 
I'm guessing that the input is relatively large (several megabytes) but I can't say for sure.

> On last commit 51ee3fb we add a protection against memory over use. Is it possible for you to test last snapshot and tell us if it's work better this way ?

Thanks!

> Is it possible for you to test last snapshot and tell us if it's work better this way ?

I will try to reproduce this error with a given input and let you know if I can still reproduce it with the latest snapshot or not.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_

- @Mogztter are you OK with the @arnaudroques's answer?

Then;
- It is possible to close the ticket?
Or have you some elements to provide?

Regards.

**Comment by Mogztter** [comment]
I wasn't able to reproduce this issue so I believe it's fixed. However, I still think it would be good to be able to disable this feature (using an environment variable).
