### ISSUE TITLE
 Could not initialize class net.sourceforge.plantuml.creole.command.CommandCreoleEmoji

### ISSUE THREAD

**Issue by qbolec** [plantuml/plantuml#829]
Hi, I've downloaded the version from http://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2021.16.jar/download and it fails with:
```
$ java -jar "C:/ade\plantuml.jar" ../mysql-bin/doxygen/html/inline_umlgraph_svghtml.pu
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.plantuml.creole.command.CommandCreoleEmoji
        at net.sourceforge.plantuml.creole.legacy.StripeSimple.<init>(StripeSimple.java:164)
        at net.sourceforge.plantuml.creole.legacy.CreoleStripeSimpleParser.createStripe(CreoleStripeSimpleParser.java:146)
        at net.sourceforge.plantuml.creole.legacy.CreoleParser.createStripe(CreoleParser.java:106)
        at net.sourceforge.plantuml.creole.legacy.CreoleParser.createSheet(CreoleParser.java:140)
        at net.sourceforge.plantuml.cucadiagram.Display.getCreole(Display.java:557)
        at net.sourceforge.plantuml.cucadiagram.Display.create0(Display.java:527)
        at net.sourceforge.plantuml.cucadiagram.Display.create7(Display.java:488)
        at net.sourceforge.plantuml.graphic.GraphicStrings.getTextBlock(GraphicStrings.java:149)
        at net.sourceforge.plantuml.graphic.GraphicStrings.calculateDimensionInternal(GraphicStrings.java:177)
        at net.sourceforge.plantuml.graphic.GraphicStrings.drawU(GraphicStrings.java:155)
        at net.sourceforge.plantuml.UmlDiagram$1.drawU(UmlDiagram.java:185)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.getFinalDimension(ImageBuilder.java:326)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:260)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.write(ImageBuilder.java:247)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:195)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:152)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:145)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:178)
        at net.sourceforge.plantuml.Run.manageFileInternal(Run.java:517)
        at net.sourceforge.plantuml.Run.processArgs(Run.java:400)
        at net.sourceforge.plantuml.Run.manageAllFiles(Run.java:367)
        at net.sourceforge.plantuml.Run.main(Run.java:202)
```
^ this is Git Bash, on Windows 10, I can provide the full file if needed, but it starts with:
```
@startuml inline_umlgraph_1.svg
  state ARCH_BLOCK_INIT
  state ARCH_BLOCK_ACTIVE
  state ARCH_BLOCK_READY_TO_FLUSH
  state ARCH_BLOCK_FLUSHED

  [*] -down-> ARCH_BLOCK_INIT
  ARCH_BLOCK_INIT -> ARCH_BLOCK_ACTIVE : Writing page ID
  ARCH_BLOCK_ACTIVE -> ARCH_BLOCK_READY_TO_FLUSH : Block is full
  ARCH_BLOCK_READY_TO_FLUSH -> ARCH_BLOCK_FLUSHED : Block is flushed
  ARCH_BLOCK_FLUSHED --> ARCH_BLOCK_ACTIVE : Writing page ID
  ARCH_BLOCK_FLUSHED -down-> [*]
@enduml
```
Perhaps it's related to https://github.com/plantuml/plantuml/commit/1d6d3e847752b30753c43190374c93caef4063d0 ?

**Comment by qbolec** [comment]
I've tried the same invocation with the previous version https://sourceforge.net/projects/plantuml/files/plantuml-nodot.1.2021.15.jar/download and it worked fine.

**Comment by arnaudroques** [comment]
Sorry about that and dhanks for the feedback.
We've upload a [patched version](https://sourceforge.net/projects/plantuml/files/1.2021.16/plantuml-nodot.1.2021.16.patched.jar/download) that should work fine.
Tell us if you have some more issues.

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @qbolec for the report.
- Thanks PlantUML team for your work.

Regards.
