### ISSUE TITLE
Potential infinite loop on timing diagram

### ISSUE THREAD

**Issue by Mogztter** [plantuml/plantuml#836]
I'm using PlantUML version 1.2021.16(Wed Dec 08 17:25:22 GMT 2021) and the following diagram produces an infinite loop (or at least an extremely long processing):

```
@startuml
scale 100 as 0 pixels
concise "identificatin-app" as idapp
concise "CSABackApp" as CB

idapp is idle
CB is idle

@idapp
0 is "идентификация"
+250 is "запрос в процессинг"

@CB
0 is "обновление профиля"
@enduml
```

```
io.vertx.core.VertxException: Thread blocked
	at app//net.sourceforge.plantuml.timingdiagram.TimingRuler.drawTimeAxis(TimingRuler.java:190)
	at app//net.sourceforge.plantuml.timingdiagram.TimingDiagram.drawInternal(TimingDiagram.java:164)
	at app//net.sourceforge.plantuml.timingdiagram.TimingDiagram.access$000(TimingDiagram.java:72)
	at app//net.sourceforge.plantuml.timingdiagram.TimingDiagram$1.drawU(TimingDiagram.java:107)
	at app//net.sourceforge.plantuml.ugraphic.ImageBuilder.getFinalDimension(ImageBuilder.java:326)
	at app//net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:260)
	at app//net.sourceforge.plantuml.ugraphic.ImageBuilder.write(ImageBuilder.java:247)
	at app//net.sourceforge.plantuml.timingdiagram.TimingDiagram.exportDiagramInternal(TimingDiagram.java:100)
	at app//net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:134)
	at app//net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
	at app//io.kroki.server.service.Plantuml.convert(Plantuml.java:280)
	at app//io.kroki.server.service.Plantuml.lambda$convert$5(Plantuml.java:236)
	at app//io.kroki.server.service.Plantuml$$Lambda$194/0x00000001002ccc40.handle(Unknown Source)
	at app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$198/0x00000001002cb040.handle(Unknown Source)
	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at app//io.vertx.core.impl.ContextImpl$$Lambda$196/0x00000001002cb840.run(Unknown Source)
	at app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at app//io.vertx.core.impl.TaskQueue$$Lambda$103/0x00000001001adc40.run(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base@11.0.9.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.9.1/java.lang.Thread.run(Unknown Source)
```

For reference, I tried to run the above diagram on plantuml.com and got a 504 Gateway Timeout:

```
http://www.plantuml.com/plantuml/png/HOr1JiGW58RtdEA5hJ514_STE88d81IJ5nbiX4bSMcDcwrN6QcDZqtg5nus4Yhhx-Vd-xpKXwljus3iMZ7OMBeG07K10Xm_M1MRklC5WWMDhVSGRD3gYFzTTnmk7RKx_aBhUIMrkT_LNISOs0h2WpZ8b_o9hViQYD9mcUgUHblH4KthEhqywfMFEBvoTNLvLw8DEz9KUQKqzq00r7sbCVUhpQA4tdiLA_bfNUitbIWFDnPwHiQws8tFHDzQtXxtx1W00
```
```
Request Method: GET
Status Code: 504 Gateway Timeout
```

**Comment by swmatisa** [comment]
Hello,
"scale 100 as 0 pixels" is a bad idea

Use "scale 100 as <x> pixels" where <x> is bigger than 0 and there is no problem

**Comment by Mogztter** [comment]
Hello,

> "scale 100 as 0 pixels" is a bad idea
> Use "scale 100 as <x> pixels" where <x> is bigger than 0 and there is no problem

There's no doubt but I do no control the input. Users can send invalid diagrams but it should not produce an infinite loop.
I guess PlantUML could check if <x> is greater than 0 in "as <x> pixels" and if not abort the process?

**Comment by arnaudroques** [comment]
> There's no doubt but I do no control the input. Users can send invalid diagrams but it should not produce an infinite loop.
> I guess PlantUML could check if is greater than 0 in "as pixels" and if not abort the process?

Yes, thanks for the feedback. Don't worry, we are going to fix this ! Probably today

**Comment by arnaudroques** [comment]
So it's [fixed online](https://www.plantuml.com/plantuml/uml/HOr1JiGW58RtdEA5hJ514_STE88d81IJ5nbiX4bSMcDcwrN6QcDZqtg5nus4Yhhx-Vd-xpKXwljus3iMZ7OMBeG07K10Xm_M1MRklC5WWMDhVSGRD3gYFzTTnmk7RKx_aBhUIMrkT_LNISOs0h2WpZ8b_o9hViQYD9mcUgUHblH4KthEhqywfMFEBvoTNLvLw8DEz9KUQKqzq00r7sbCVUhpQA4tdiLA_bfNUitbIWFDnPwHiQws8tFHDzQtXxtx1W00) and [with last snapshot](https://github.com/plantuml/plantuml/releases/tag/snapshot).

Please tell us if you find some more issues!
And [many thanks for your support](https://github.com/sponsors/plantuml)!!!

**Comment by Mogztter** [comment]
Excellent, thanks for the quick fix 🎉

> Please tell us if you find some more issues!

You can count on me 😉 

> And many thanks for your support!!!

I was surprised to be the first sponsor on GitHub, PlantUML is a great project, keep up the good work 🥇

**Comment by The-Lum** [comment]
Hi all,

_[This is an Issue Review]_
This is now fixed.
- Thanks @Mogztter for the report.
- Thanks PlantUML team for your work.
	
Regards.
