### ISSUE TITLE
Access problem?

### ISSUE THREAD

**Issue by msdobrescu** [plantuml/plantuml#982]
I run plantuml under linux. Gentoo compiled package or compiled release from GH give the same errors and can't generate the image (an empty .png is created).

```
javax.imageio.IIOException: Can't create cache file!
        at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1359)
        at net.sourceforge.plantuml.security.SImageIO.read(SImageIO.java:74)
        at net.sourceforge.plantuml.version.PSystemVersion.getImage(PSystemVersion.java:119)
        at net.sourceforge.plantuml.version.PSystemVersion.getPlantumlSmallIcon(PSystemVersion.java:97)
        at net.sourceforge.plantuml.version.PSystemVersion.getPlantumlSmallIcon2(PSystemVersion.java:143)
        at net.sourceforge.plantuml.swing.MainWindow.<init>(MainWindow.java:162)
        at net.sourceforge.plantuml.Run.main(Run.java:171)
Caused by: java.nio.file.AccessDeniedException: /tmp/imageio8332605445475580699.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.createFile(Files.java:648)
        at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
        at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
        at java.base/java.nio.file.Files.createTempFile(Files.java:913)
        at java.desktop/javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
        at java.desktop/com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
        at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
        ... 7 more
Issue in flashcode generation java.lang.IllegalArgumentException: Memory error
javax.imageio.IIOException: Can't create cache file!
        at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:361)
        at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1359)
        at net.sourceforge.plantuml.security.SImageIO.read(SImageIO.java:74)
        at net.sourceforge.plantuml.fun.IconLoader.getIconSlow(IconLoader.java:92)
        at net.sourceforge.plantuml.fun.IconLoader.getIcon(IconLoader.java:78)
        at net.sourceforge.plantuml.fun.IconLoader.getRandom(IconLoader.java:57)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:180)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:152)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:145)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:178)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:94)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:90)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.AccessDeniedException: /tmp/imageio5749325616209491149.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.createFile(Files.java:648)
        at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
        at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
        at java.base/java.nio.file.Files.createTempFile(Files.java:913)
        at java.desktop/javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:102)
        at java.desktop/com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
        at java.desktop/javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
        ... 18 more
javax.imageio.IIOException: Can't create cache file!
        at java.desktop/javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:423)
        at net.sourceforge.plantuml.security.SImageIO.createImageOutputStream(SImageIO.java:54)
        at net.sourceforge.plantuml.png.PngIOMetadata.writeInternal(PngIOMetadata.java:103)
        at net.sourceforge.plantuml.png.PngIOMetadata.writeWithMetadata(PngIOMetadata.java:67)
        at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:79)
        at net.sourceforge.plantuml.png.PngIO.write(PngIO.java:71)
        at net.sourceforge.plantuml.ugraphic.g2d.UGraphicG2d.writeToStream(UGraphicG2d.java:219)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.writeImageInternal(ImageBuilder.java:283)
        at net.sourceforge.plantuml.ugraphic.ImageBuilder.write(ImageBuilder.java:247)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:195)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramError(UmlDiagram.java:152)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:145)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:178)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:209)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:93)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:178)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:94)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:90)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.nio.file.AccessDeniedException: /tmp/imageio11050965978124322151.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.createFile(Files.java:648)
        at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:137)
        at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:160)
        at java.base/java.nio.file.Files.createTempFile(Files.java:913)
        at java.desktop/javax.imageio.stream.FileCacheImageOutputStream.<init>(FileCacheImageOutputStream.java:88)
        at java.desktop/com.sun.imageio.spi.OutputStreamImageOutputStreamSpi.createOutputStreamInstance(OutputStreamImageOutputStreamSpi.java:68)
        at java.desktop/javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
        ... 21 more
```
Other java apps work fine.

What could be the reason?

**Comment by arnaudroques** [comment]
> What could be the reason?

It looks like the application cannot access to /tmp:
Caused by: java.nio.file.AccessDeniedException: /tmp/imageio8332605445475580699.tmp

This is probably the cause of the issue.

**Comment by msdobrescu** [comment]
Indeed, but why? It works as root.

**Comment by soloturn** [comment]
openjdk has /tmp hardcoded which can be overwritten by something like
```
export _JAVA_OPTIONS=-Djava.io.tmpdir=/new/tmp/dir
```

to make /tmp available is a linux thing then, in your case specific to gentoo, or your system, so not really plantuml. so this ticket shoudl be closed.

some information anyway. on systemd managed systems the default can be seen like this:
```
> systemd-path | grep tmp
temporary: /tmp
temporary-large: /var/tmp
tmpfiles: /usr/lib/tmpfiles.d
```
it is possible the XDG_RUNTIME_DIR is used, here e.g. for user id 1000:
```
> echo $XDG_RUNTIME_DIR
/run/user/1000
```

see here for details:
* jdk default direcotry on linux is /tmp, hardcoded: https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L1317 
" https://systemd.io/TEMPORARY_DIRECTORIES/
* https://stackoverflow.com/questions/1924136/environment-variable-to-control-java-io-tmpdir
* https://stackoverflow.com/questions/51324406/how-to-specify-a-unique-java-io-tmpdir-for-each-user-of-a-multi-user-eclipse-ins
* https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html

**Comment by msdobrescu** [comment]
Hi, it seems there is something broken related to java. I have also one app failing due to an invalid pointer error.
I think this ticket can be closed indeed, although I have no exact clue regarding the cause now.
